const skills = [
  {
    id: 'shadcn-ui',
    outputType: 'html',
    author: 'shadcn',
    addedDate: '2026-08-15',
    name: 'shadcn/ui',
    category: '综合组件库',
    github: 'https://github.com/shadcn-ui/ui',
    website: 'https://ui.shadcn.com',
    stars: 122760,
    version: 'v4.19.1',
    updated: '2026-08',
    triggerSummary: '当你用 React + Tailwind 做项目需要 UI 组件时就调用它 —— 不是 npm 安装，而是把组件源码直接复制到你项目里，完全可控、可定制。',

    workflow: [
      { step: 1, title: '初始化项目', desc: '创建 React + TypeScript + Tailwind CSS 项目，配置路径别名和 Tailwind 主题' },
      { step: 2, title: '安装 shadcn/ui', desc: '运行 CLI 命令初始化，选择框架（Next.js/Vite/Remix）、基础颜色和 CSS 变量' },
      { step: 3, title: '选择所需组件', desc: '从组件库中选择需要的组件（Button、Card、Dialog、Form、Table等），CLI 自动复制源码' },
      { step: 4, title: '定制组件样式', desc: '修改组件源码中的 Tailwind 类名，调整配色、间距、圆角等，完全不受组件库限制' },
      { step: 5, title: '组合构建页面', desc: '将多个组件组合成完整页面，配合 React 状态管理实现交互逻辑' },
      { step: 6, title: '主题与暗色模式', desc: '配置 CSS 变量实现主题切换，支持亮色/暗色模式和品牌色定制' },
    ],    officialIntro: 'shadcn/ui 是一套可访问、可定制的组件集合，你可以直接复制粘贴到自己的应用中。免费、开源，用于构建你自己的组件库。基于 TypeScript、Tailwind CSS 和 Radix UI 原语构建，支持 Next.js、Vite、Remix、Astro 等多种框架，提供 CLI 工具安装和管理组件，以及注册表系统发布和分发代码。',
    suitableFor: [
      { type: 'SaaS 产品后台', desc: '组件丰富，表单/表格/导航齐全' },
      { type: '企业管理系统', desc: '可控性强，易于深度定制扩展' },
      { type: '数据仪表盘', desc: '配合图表库，适合数据密集型界面' },
      { type: '开发者工具', desc: '技术风格，文档/控制台/API 管理' },
      { type: '电商商家后台', desc: '订单/商品/用户管理等复杂表单' },
      { type: 'CRM/ERP 系统', desc: '中后台场景，组件可组合性强' },
    ],
    plainDesc: '你用 React + Tailwind 做项目，需要按钮、卡片、弹窗这些 UI 组件时就用它。跟其他组件库不一样，它不是 npm 安装，而是把组件源码直接复制到你项目里，想怎么改就怎么改，完全不受组件库限制。',
    capabilities: ['组件源码复制', 'Tailwind 样式系统', 'Radix UI 原语', '主题定制', '可访问性', 'TypeScript 支持'],
    components: [
      { name: 'Button', desc: '多种变体和尺寸的按钮组件', type: 'button' },
      { name: 'Card', desc: '灵活的内容卡片容器', type: 'card' },
      { name: 'Dialog', desc: '模态对话框，支持嵌套和表单', type: 'dialog' },
      { name: 'Dropdown Menu', desc: '下拉菜单，支持分组和快捷方式', type: 'dropdown' },
      { name: 'Form', desc: '基于 React Hook Form 的表单组件', type: 'form' },
    ],
    examples: [
      { name: 'Dashboard 仪表盘', desc: '数据看板布局，含侧边栏、统计卡片、图表区域', type: 'dashboard' },
      { name: 'Landing Page 落地页', desc: '营销落地页，含 Hero、特性网格、定价、CTA', type: 'landing' },
    ],
    pageDemos: [
      { name: 'Web Dashboard', device: 'web', type: 'dashboard' },
      { name: 'Mobile App', device: 'mobile', type: 'mobile-app' },
      { name: 'Landing Page', device: 'web', type: 'landing' },
    ],
    conversations: [
      { q: '帮我做一个 SaaS 产品的定价页面', a: '使用 shadcn/ui 的 Card、Button、Badge 组件构建三档定价卡片，含月度/年度切换、特性对比列表和 CTA 按钮。', output: '定价页 · 3 档方案 · 年付优惠' },
      { q: '需要一个用户设置页面', a: '使用 Tabs 组织设置分类，配合 Input、Switch、Select 表单组件，底部放置保存按钮。', output: '设置页 · 5 个分类 · 表单验证' },
      { q: '做一个数据表格页面', a: '使用 Table 组件配合 Pagination、Badge 状态标签，支持列排序和行选择。', output: '表格页 · 排序 · 分页 · 批量操作' },
      { q: '帮我构建一个登录注册页面', a: '使用 Card 容器包裹表单，Input + Label 组合，Button 提交，底部链接切换登录/注册。', output: '认证页 · 登录/注册切换 · 表单校验' },
      { q: '需要一个通知中心组件', a: '使用 Dropdown Menu 触发通知列表，每条通知含 Avatar、标题、时间、未读标记。', output: '通知中心 · 未读标记 · 批量已读' },
    ],
    prompts: [
      { title: '构建组件库页面', text: '使用 shadcn/ui 帮我构建一个组件库展示页面，包含 Button、Card、Dialog、Form 组件的用法示例和代码片段。' },
      { title: 'SaaS 仪表盘', text: '用 shadcn/ui 做一个 SaaS 产品的管理后台仪表盘，需要侧边栏导航、统计卡片、数据表格和图表区域。' },
      { title: '电商产品页', text: '使用 shadcn/ui 组件构建一个电商产品详情页，包含产品图片轮播、规格选择、加入购物车按钮和用户评价区域。' },
      { title: '任务管理应用', text: '用 shadcn/ui 做一个任务管理应用界面，需要看板视图、任务卡片、拖拽排序、筛选和搜索功能。' },
      { title: '文档网站', text: '使用 shadcn/ui 构建一个技术文档网站，包含侧边栏目录、内容区域、代码高亮、搜索框和上一页/下一页导航。' },
    ],
    userReviews: {
      rating: 4.8, count: 1240,
      summary: 'shadcn/ui 是目前最受欢迎的 React 组件库之一，以"复制源码而非安装"的理念著称，深度整合 Tailwind CSS 和 Radix UI。',
      pros: ['完全可控的组件源码', '与 Tailwind CSS 无缝集成', '基于 Radix UI 的可访问性', '活跃的社区和持续更新', '支持主题定制和暗色模式', 'TypeScript 类型完善', '组件覆盖全面', '文档质量高'],
      cons: ['需要手动管理组件版本', '首次配置有一定门槛', '部分复杂组件需自行扩展', '不适合非 Tailwind 项目', '组件样式需自行统一'],
      articles: [
        { title: 'shadcn/ui 官方文档 — 组件与主题定制', source: 'ui.shadcn.com', url: 'https://ui.shadcn.com/docs' },
        { title: 'Major Update: Base UI & Radix UI Support with Shadcn Styles', source: 'Shadcn Studio', url: 'https://shadcnstudio.com/blog/major-update-base-ui-radix-ui-support/' },
        { title: 'The AI-Native shadcn/ui Component Library for React', source: 'shadcn.io', url: 'https://www.shadcn.io/' },
        { title: 'shadcn/ui Cheatsheet — 42+ 组件速查', source: 'GitHub', url: 'https://github.com/shadcnstore/shadcn-cheatsheet/' },
        { title: 'shadcn/ui 实战：从0搭建企业级组件库', source: '小红书', url: 'https://www.xiaohongshu.com/search_result?keyword=shadcn%2Fui%20%E5%AE%9E%E6%88%98', platform: 'xiaohongshu' },
        { title: '深度解析 shadcn/ui 为什么成为 AI 生成默认选择', source: '微信公众号', url: 'https://weixin.sogou.com/weixin?type=2&query=shadcn%2Fui%20%E6%B7%B1%E5%BA%A6%E8%A7%A3%E6%9E%90', platform: 'wechat' }],
    },
  },
  {
    id: 'ui-ux-pro-max',
    outputType: 'html',
    name: 'UI/UX Pro Max',
    author: 'nextlevelbuilder',
    addedDate: '2026-08-18',
    version: 'v2.15.0',
    stars: 123983,
    github: 'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill',
    website: 'https://www.uupm.cc/',
    category: '综合设计系统',
    triggerSummary: '当你需要 AI 帮你做 UI/UX 设计时就调用它 —— 不管是从零做页面、选配色字体、审查现有界面、修交互 bug，还是跨平台（Web/iOS/Android）生成代码',
    officialIntro: 'An AI skill that provides design intelligence for building professional UI/UX across multiple platforms and frameworks. v2.0 旗舰功能是智能设计系统生成器，通过 AI 推理引擎分析项目需求，几秒内生成完整的定制化设计系统。包含 79 种可搜索 UI 样式、192 个行业推理规则、192 套配色方案、74 组字体配对、25 种图表类型，支持 22 种技术栈和 119 条 UX 指南。',
    plainDesc: '你让 AI 写网页但总觉得"不好看"？这个 skill 就是给 AI 装了个"设计师大脑"。你说一句"做个美容店官网"，它会自动帮你选好配色、字体、排版风格、页面结构，甚至告诉你哪些坑不能踩。支持 20 多种技术栈，Web、iOS、Android 都能用。',
    suitableFor: [
      { type: 'SaaS 产品官网', desc: 'B2B/SaaS 产品的营销落地页和功能展示页' },
      { type: '移动端 APP UI', desc: 'iOS/Android 应用界面设计，支持 SwiftUI/Flutter/React Native' },
      { type: '电商品牌页', desc: '品牌电商首页、产品详情页、促销活动页' },
      { type: '数据仪表盘', desc: '后台管理系统、数据可视化面板、BI 报表' },
      { type: '创意作品集', desc: '设计师/开发者个人作品集、创意展示网站' },
      { type: '企业官网', desc: '公司官网、品牌介绍页、企业文化展示' },
    ],
    capabilities: [
      '智能设计系统生成', '79种UI风格库', '192套行业配色', '74组字体配对',
      '22种技术栈支持', '119条UX准则',
    ],
    components: [
      '设计系统生成器', '风格搜索引擎', '配色方案库', '字体配对推荐', 'UX反模式检测',
    ],
    examples: [
      { title: '美容SPA官网', desc: '自动生成柔和配色+优雅字体+社交证明页面结构' },
      { title: '金融科技仪表盘', desc: '推荐数据密集型布局+专业蓝配色+25种图表类型' },
    ],
    pageDemos: [
      { type: 'saas-redesign', title: 'SaaS 产品官网', desc: 'AI 自动匹配行业风格和配色' },
      { type: 'fintech-dashboard', title: '金融数据仪表盘', desc: '25种图表类型推荐+数据密集布局' },
      { type: 'mobile-app', title: '移动端 APP 界面', desc: '支持 SwiftUI/Flutter/React Native' },
    ],
    conversations: [
      { q: '帮我做一个 AI 聊天机器人的官网', a: '已生成设计系统：科技蓝配色+Geist字体+Hero-Centric布局+功能展示区，避免AI紫粉渐变', output: '完整 landing page 代码' },
      { q: '这个按钮的交互有问题，帮我修一下', a: '检测到3个UX问题：缺少hover状态、点击无反馈、焦点不可见，已按WCAG AA修复', output: '修复后的组件代码' },
      { q: '做一个牙科诊所的预约页面', a: '匹配医疗行业规则：信任导向布局+柔和绿配色+易读字体+预约表单+社会证明', output: '预约页面完整代码' },
      { q: '我想要玻璃拟态风格的登录页', a: '已选择 Glassmorphism 风格：半透明卡片+背景模糊+微妙边框+柔和阴影，注意性能优化', output: '登录页代码' },
      { q: '帮我审查一下这个电商页面的设计', a: '发现5个问题：CTA不突出、图片加载慢、移动端适配差、配色冲突、缺少信任标识', output: '审查报告+修复建议' },
    ],
    prompts: [
      { title: '生成行业定制设计系统', text: '使用 UI/UX Pro Max 为我的 [行业] 产品生成完整设计系统，包括配色、字体、页面结构和反模式清单' },
      { title: '从零构建落地页', text: 'Build a landing page for my [产品类型] using UI/UX Pro Max, include hero, features, testimonials, pricing and CTA sections' },
      { title: '设计审查与优化', text: 'Review my current UI using UX Pro Max guidelines, identify anti-patterns and accessibility issues, then provide fixed code' },
      { title: '移动端 APP 设计', text: 'Design a mobile app UI for [APP类型] using SwiftUI/Flutter, follow platform-specific guidelines from UI/UX Pro Max' },
      { title: '特定风格实现', text: 'Create a [风格名如 Glassmorphism/Bento Grid/Brutalism] style page for [用途], use the style guidelines from UI/UX Pro Max' },
    ],
    userReviews: {
      rating: 4.8,
      count: 2847,
      summary: 'UI/UX Pro Max 是目前最全面的 AI 设计智能 skill，通过 192 条行业推理规则自动生成定制化设计系统，让 AI 编码助手具备专业设计师的判断力。',
      pros: [
        '192条行业推理规则，覆盖SaaS/金融/医疗/电商等8大领域',
        '79种可搜索UI风格，含玻璃拟态/Bento/野兽派等流行风格',
        '智能设计系统生成器，几秒输出配色+字体+布局+反模式清单',
        '支持22种技术栈，Web/iOS/Android全平台覆盖',
        '119条UX准则+可访问性检查，交付前自动验证',
        'BM25搜索引擎，精准匹配产品类型和设计风格',
        '活跃社区维护，每月更新风格库和推理规则',
        'MIT开源，免费商用，支持CLI一键安装',
      ],
      cons: [
        '首次安装需要配置CLI，对新手有一定门槛',
        '设计系统生成依赖Python脚本，部分环境需额外配置',
        '风格库虽多但活跃风格仅50种，其余需精确匹配触发',
        'Premium版功能（品牌设计/Logo）需付费，开源版不含',
        '中文文档不够完善，主要文档为英文',
      ],
      articles: [
        { title: 'Vibe Coding - 用 UI UX Pro Max 把 AI 编码助手变成"会设计"的前端搭档', url: 'https://blog.csdn.net/yangshangwei/article/details/156618301', platform: 'CSDN' },
        { title: 'UI UX Pro Max Skill 深度评测：192条规则让 AI 懂设计', url: 'https://rightaichoice.com/tools/ui-ux-pro-max-skill', platform: 'RightAIChoice' },
        { title: 'Stop Letting Agents Guess UI: Installing and Using UI UX Pro Max the Right Way', url: 'https://blog.margrop.net/en/post/ui-ux-pro-max-agent-skill-guide/', platform: 'blog.margrop.net' },
        { title: 'UI/UX Pro Max Skill — The Game Changer That Gives Your Product Team a Built-In UX Designer', url: 'https://www.nuttadech.com/en/blog/uiux-pro-max-skill-game-changer', platform: 'nuttadech.com' },
        { title: 'UI UX Pro Max を試す — Claude Code に「デザインの脳」を差し込むスキル', url: 'https://ai-gp.net/en/blog/ui-ux-pro-max-review/', platform: 'AI Generation Prompt' },
      ],
    },
    workflow: [
      { step: 1, title: '需求输入', desc: '用户描述 UI/UX 需求（构建/设计/审查/修复/优化），可指定行业、风格、技术栈' },
      { step: 2, title: '多域并行搜索', desc: '5个并行搜索：192个产品类型匹配、79种风格推荐、192套配色选择、34种页面结构、74组字体配对' },
      { step: 3, title: '推理引擎分析', desc: 'BM25排序匹配产品→UI规则，应用风格优先级，过滤行业反模式，处理JSON条件决策规则' },
      { step: 4, title: '设计系统输出', desc: '生成完整设计系统：页面结构+视觉风格+配色方案+字体排版+动效建议+反模式清单+交付前检查项' },
      { step: 5, title: '代码实现', desc: '按设计系统规范实现 UI 代码，应用正确的配色、字体、间距、交互，遵循技术栈特定指南' },
      { step: 6, title: '交付前验证', desc: '自动检查：SVG图标替代emoji、cursor-pointer、对比度4.5:1、焦点可见、reduced-motion、响应式375-1440px' },
    ],
  },
  {
    id: 'taste-skill',
    outputType: 'html',
    author: 'Leonxlnx',
    addedDate: '2026-08-20',
    name: 'Taste Skill',
    category: '设计品味审计',
    github: 'https://github.com/Leonxlnx/taste-skill',
    website: 'https://www.tasteskill.dev',
    stars: 83429,
    version: 'v2.0.0',
    updated: '2026-08',
    subSkills: [
      { name: 'taste-skill', installName: 'design-taste-frontend', category: '实现类', familyColor: 'blue', subtitle: '上下文驱动 · 全能适配', plainDesc: 'Taste 家族的主力。你要从零做落地页、作品集、产品官网时用它，它会读需求、定风格、输出完整代码。', steps: ['读需求（Brief Inference）', '定三旋钮 8/6/4（按需求覆盖）', '映射设计系统 or 诚实标注美学', '从 14 章规则里"按需取用"', '60+ 项 Pre-Flight 机械检查'],
        prompt: '创建一个高端创意工作室的落地页，包含Hero区域、服务介绍、作品集展示、客户评价和联系表单。要求设计感强、排版精致、动效流畅。',
        model: '豆包 2.1 Turbo + design-taste-frontend skill v2.1',
        projectType: '高端创意工作室落地页'
      },
      { name: 'taste-skill-v1', installName: 'design-taste-frontend-v1', category: '实现类', familyColor: 'blue', subtitle: '原版保留 · 精确回退', plainDesc: 'Taste 的旧版本。之前项目用 v1，升级 v2 后行为不对时用它回退，保证行为一致。', steps: ['依赖 v1 精确行为的项目使用', 'v2 默认版不兼容时回退', '保留 v1 全部规则和旋钮', '不引入 v2 新特性', '稳定输出，行为可预测'],
        prompt: '创建一个SaaS产品官网，包含Hero、功能特性、定价方案、客户评价和FAQ。使用v1版本的设计规则。',
        model: '豆包 2.1 Turbo + design-taste-frontend skill v1.0',
        projectType: 'SaaS产品官网'
      },
      { name: 'gpt-tasteskill', installName: 'gpt-taste', category: '实现类', familyColor: 'blue', subtitle: '强制随机化 · Awwwards 单流派', plainDesc: 'Taste 的"激进版"。想要 Awwwards 那种大胆、有创意、动效强的设计时用它，随机化选元素避免千篇一律。', steps: ['用 prompt 长度做随机种子', '"掷骰子"选 hero/字体/组件/GSAP', '套 AIDA 骨架（Attention→Action）', '强制 GSAP 高动效（禁静态）', '输出前 自证清单'],
        prompt: '创建一个Awwwards级别的创意 agency 网站，要求大胆的实验性布局、强烈的视觉冲击、GSAP高级动效、随机化的元素选择。',
        model: '豆包 2.1 Turbo + gpt-taste skill（强制随机化 + GSAP高动效）',
        projectType: '创意Agency网站（Awwwards风格）'
      },
      { name: 'soft-skill', installName: 'high-end-visual-design', category: '实现类', familyColor: 'green', subtitle: '柔和对比 · 大量留白 · 昂贵感', plainDesc: '想要"很贵"的设计感时用它。柔和配色、大量留白、高级字体、弹簧动效，适合高端品牌、奢侈品、创意工作室。', steps: ['柔和对比配色（低饱和高级色）', '大量留白营造呼吸感', '高级字体选择和层级', '弹簧动效（Spring Physics）', '细节打磨到像素级'],
        prompt: '创建一个奢侈品牌官网，包含产品展示、品牌故事、精品店定位和会员专区。要求柔和对比、大量留白、高级字体、弹簧动效。',
        model: '豆包 2.1 Turbo + high-end-visual-design skill（高端代理风格）',
        projectType: '奢侈品牌官网'
      },
      { name: 'minimalist-skill', installName: 'minimalist-ui', category: '实现类', familyColor: 'green', subtitle: 'Notion/Linear 风格 · 编辑级界面', plainDesc: '喜欢 Notion、Linear 那种极简、干净、克制的界面时用它。中性配色、清晰结构，适合工具类、SaaS 产品。', steps: ['克制配色（中性色为主）', '清晰结构和信息层级', '编辑级产品界面标准', '极简交互和微动效', '内容优先，装饰最少'],
        prompt: '创建一个Notion/Linear风格的项目管理工具界面，包含侧边栏导航、任务列表、看板视图、统计面板。要求极简、干净、克制。',
        model: '豆包 2.1 Turbo + minimalist-ui skill（编辑级界面标准）',
        projectType: '项目管理SaaS工具界面'
      },
      { name: 'brutalist-skill', installName: 'industrial-brutalist-ui', category: '实现类', familyColor: 'green', subtitle: '瑞士排版 · 强对比 · 硬核机械感', plainDesc: '想要硬核、个性、有冲击力的设计时用它。瑞士排版、强对比、实验性布局，适合音乐、潮流、科技品牌。', steps: ['瑞士排版网格系统', '强对比配色（黑白+强调色）', '实验性布局和不对称', '粗野字体和大字号', '硬核机械感视觉语言'],
        prompt: '创建一个独立音乐厂牌的官网，要求瑞士排版网格、强对比黑白配色、实验性不对称布局、粗野大字号、硬核机械感。',
        model: '豆包 2.1 Turbo + industrial-brutalist-ui skill（瑞士排版+粗野主义）',
        projectType: '独立音乐厂牌官网'
      },
      { name: 'stitch-skill', installName: 'stitch-design-taste', category: '实现类', familyColor: 'green', subtitle: 'Google Stitch 兼容 · DESIGN.md 导出', plainDesc: '用 Google Stitch（谷歌的 AI 编程工具）做项目时用它。生成 Stitch 能直接读取的 DESIGN.md 设计规范文件。', steps: ['适配 Google Stitch 工作流', '生成 DESIGN.md 设计规范文件', '包含配色、字体、组件规范', 'Stitch 可直接读取使用', '保持 taste-skill 设计标准'],
        prompt: '创建一个Google Stitch兼容的设计系统文档页面，输出DESIGN.md格式，包含设计令牌、组件规范、布局原则。',
        model: '豆包 2.1 Turbo + stitch-design-taste skill（DESIGN.md导出）',
        projectType: '设计系统文档页'
      },
      { name: 'redesign-skill', installName: 'redesign-existing-projects', category: '实现类', familyColor: 'orange', subtitle: '先审计 → 再定点修复，不重写', plainDesc: '已有项目但设计很丑想改版时用它。不重写整个项目，先审计问题，再定点修复布局、间距、样式。', steps: ['审计现有 UI 问题清单', '定位布局、间距、层级问题', '修复样式和交互 bug', '保留原有功能和结构', '输出前后对比和修改说明'],
        prompt: '对一个现有的企业官网进行改版升级，先审计现有设计的问题，然后定点修复导航、Hero、卡片排版和响应式，不重写整个项目。',
        model: '豆包 2.1 Turbo + redesign-existing-projects skill（审计→定点修复）',
        projectType: '企业官网改版升级'
      },
      { name: 'image-to-code-skill', installName: 'image-to-code', category: '实现类', familyColor: 'purple', subtitle: '图→分析→代码管线', plainDesc: '你有一张设计图/参考图，想变成真实前端代码时用它。先分析图的设计语言，再写出匹配的代码。', steps: ['先生成参考图（视觉锚点）', '分析设计语言和布局结构', '提取配色、字体、间距规范', '实现匹配的前端代码', '对照原图校验还原度'],
        prompt: '分析一张高端电商产品页的设计图，提取布局结构、配色方案、字体层级、组件样式，然后输出完整的HTML/CSS代码实现。',
        model: '豆包 2.1 Turbo + image-to-code skill（图→分析→代码管线）',
        projectType: '设计图转代码（电商产品页）'
      },
      { name: 'imagegen-frontend-web', installName: 'imagegen-frontend-web', category: '图像生成类', familyColor: 'purple', subtitle: '网页逐 section 出图 · 反廉价感', plainDesc: '不想写代码，只想先看网站长什么样时用它。生成网页设计参考图（Hero、落地页、多区块），拿图再给编码 AI 实现。', steps: ['Hero 区域设计图生成', '落地页多区块连续出图', '强排版和视觉层次', '反廉价感艺术指导', '输出高保真设计参考图'],
        prompt: '生成一个高端餐厅官网的网页设计参考图，按section逐段输出：导航栏、Hero、菜单展示、餐厅环境、预订区域、页脚。',
        model: '豆包 2.1 Turbo + imagegen-frontend-web skill（网页逐section出图）',
        projectType: '高端餐厅官网设计图'
      },
      { name: 'imagegen-frontend-mobile', installName: 'imagegen-frontend-mobile', category: '图像生成类', familyColor: 'purple', subtitle: '移动端屏幕流 · iOS/Android', plainDesc: '要做手机 APP，想先看界面长什么样时用它。生成 iOS/Android 设计参考图和多屏流程图。', steps: ['iOS/Android/跨平台适配', 'mockup 场景图生成', '可读字体和触控友好布局', '连贯屏幕组（多屏流程）', '输出移动端设计参考图'],
        prompt: '生成一个健身追踪App的移动端屏幕流设计图，包含：启动页、首页仪表盘、运动记录、数据统计、个人中心，共5个屏幕。',
        model: '豆包 2.1 Turbo + imagegen-frontend-mobile skill（移动端屏幕流）',
        projectType: '健身App移动端设计图'
      },
      { name: 'brandkit', installName: 'brandkit', category: '图像生成类', familyColor: 'purple', subtitle: '品牌设计板 · 跨品类身份', plainDesc: '做新品牌，需要 Logo 方向、配色、字体、品牌视觉时用它。生成一套完整的品牌设计板。', steps: ['Logo 方向探索', '配色系统定义', '字体选择和搭配', '跨品类身份应用', '输出完整品牌设计板'],
        prompt: '生成一个新消费品牌的完整品牌套件图，包含：Logo设计、品牌配色系统、字体规范、名片设计、社交媒体模板、包装设计。',
        model: '豆包 2.1 Turbo + brandkit skill（品牌套件生成）',
        projectType: '新消费品牌VI套件'
      },
      { name: 'output-skill', installName: 'full-output-enforcement', category: '实现类', familyColor: 'amber', subtitle: '强制完整输出 · 禁占位符', plainDesc: 'AI 写代码总写一半就停、或用"// TODO"占位时用它。强制输出完整代码，不允许省略和占位。', steps: ['检测模型输出是否半成品', '强制完整代码（不省略）', '禁止占位注释（如 // TODO）', '补全被截断的部分', '输出前完整性自检'],
        prompt: '创建一个完整的多页面Web应用，强制输出完整代码，禁止使用占位符、省略号或"此处省略"。包含：登录页、仪表盘、列表页、详情页、设置页。',
        model: '豆包 2.1 Turbo + full-output-enforcement skill（强制完整输出）',
        projectType: '多页面Web应用（完整输出）'
      },
    ],
    familyStructure: {
      title: 'taste-skill 家族 · UI 技能全景',
      subtitle: '13 个技能 = 4 类 UI 技能 + 1 个辅助技能（full-output-enforcement 非 UI）',
      categories: [
        { name: '通用主控型', tagline: '从零做落地页/作品集', workflow: '读需求 → 定旋钮 → 出代码', color: 'blue', skills: [
          { name: 'design-taste-frontend', note: 'v2 主技能，最全' },
          { name: 'design-taste-frontend-v1', note: '旧版，精简' },
          { name: 'gpt-taste', note: '更严格变体，强 GSAP' },
        ]},
        { name: '既定风格型', tagline: '方向已定，只管执行', workflow: '按固定审美体系生成 UI', color: 'green', skills: [
          { name: 'high-end-visual-design', note: '高端代理' },
          { name: 'minimalist-ui', note: '极简编辑风' },
          { name: 'industrial-brutalist-ui', note: '粗野工业风' },
          { name: 'stitch-design-taste', note: '生成 DESIGN.md 给 Google Stitch' },
        ]},
        { name: '存量改版型', tagline: '已有项目升级', workflow: '先审计 → 再定点修复，不重写', color: 'orange', skills: [
          { name: 'redesign-existing-projects', note: '' },
        ]},
        { name: '图片参考型', tagline: '只出图，不出代码', workflow: '生成设计参考图，交给编码 agent', color: 'purple', skills: [
          { name: 'image-to-code', note: '图→分析→代码管线' },
          { name: 'imagegen-frontend-web', note: '网页逐 section 出图' },
          { name: 'imagegen-frontend-mobile', note: '移动端屏幕流' },
          { name: 'brandkit', note: '品牌套件图' },
        ]},
        { name: '辅助型', tagline: '非 UI', workflow: '解决输出截断问题', color: 'amber', skills: [
          { name: 'full-output-enforcement', note: '强制完整输出，禁占位符' },
        ]},
      ],
    },
    triggerSummary: '当你需要 AI 帮你做 UI/UX 设计时就调用它 —— 不管是从零做页面、选配色字体、审查现有界面、修交互 bug，还是优化响应式和无障碍。',

    workflow: [
      { step: 1, title: '读取需求（Brief Inference）', desc: 'AI 自动推断项目需求、目标用户和设计目标，不遗漏关键信息' },
      { step: 2, title: '定三旋钮 8/6/4', desc: '按需求覆盖度调节 Variance（方差）、Motion（动效）、Density（密度）三个核心旋钮' },
      { step: 3, title: '映射设计系统', desc: '映射到现有设计系统，或诚实标注美学选择，不假装是"通用最佳实践"' },
      { step: 4, title: '14 章规则按需取用', desc: '从 14 章设计规则中按需取用，不堆砌全部规则，保持设计的针对性' },
      { step: 5, title: '60+ 项 Pre-Flight 检查', desc: '交付前运行 60+ 项机械检查，确保间距、对齐、层级、对比度等基础质量' },
      { step: 6, title: '反廉价感审计', desc: '自动审计"廉价感"问题，识别模板化设计、渐变滥用、图标不一致等常见 AI 设计缺陷' },
    ],    officialIntro: 'Taste Skill 是一个为 AI 编程助手设计的"设计判断力"技能。它教会 AI 什么是好的设计，通过三个旋钮（Variance 方差 / Motion 动效 / Density 密度）调节设计风格，内置反廉价感审计规则和交付前检查清单，帮助 AI 生成摆脱模板感的高质量界面设计。包含 13 个子技能，覆盖从零做页面、既定风格生成、存量改版、图像参考、完整输出强制等全场景，支持多种 AI 编程工具。',
    suitableFor: [
      { type: '高端品牌官网', desc: '反廉价感审计，设计品质有保障' },
      { type: '创意工作室/设计机构', desc: '13 个子技能，风格多样可定制' },
      { type: '个人作品集', desc: '三旋钮调节，避免千篇一律' },
      { type: 'SaaS 产品营销页', desc: '高动效+强排版，提升转化' },
      { type: '奢侈品/高端消费品牌', desc: '高端视觉子技能，昂贵感营造' },
      { type: '科技创业公司官网', desc: '极简/粗野/高端多风格可选' },
    ],
    plainDesc: '你让 AI 帮你写前端代码，但生成的页面总是很丑、像模板、有"廉价感"时就用它。它会教 AI 什么是好设计，通过三旋钮（方差/动效/密度）调节风格，还会自动审计"廉价感"问题，适合对设计质量有要求、不想做出来的东西千篇一律的场景。',
    capabilities: ['需求推断引擎', '三旋钮设计调节', '反廉价感审计', '字体层级校准', '动效强度控制', '配色一致性锁定'],
    components: [
      { name: 'Design Dial Controller', desc: '三旋钮调节器：Variance / Motion / Density', type: 'dial-controller' },
      { name: 'Brief Inference Card', desc: '需求推断卡片，自动分析设计方向', type: 'brief-inference' },
      { name: 'Anti-Slop Audit Panel', desc: '反廉价感审计面板，检测 AI 模板痕迹', type: 'anti-slop' },
      { name: 'Typography Hierarchy', desc: '字体层级校准器，含字号/行高/字重系统', type: 'typo-hierarchy' },
      { name: 'Motion Preset Selector', desc: '动效强度预设选择器', type: 'motion-preset' },
    ],
    examples: [
      { name: 'SaaS 落地页重设计', desc: '深色高端风，从普通模板到 Awwwards 级别的蜕变', type: 'saas-redesign' },
      { name: '设计师作品集审计', desc: '审计报告风格，逐项标注问题并给出修复方案', type: 'portfolio-audit' },
    ],
    pageDemos: [
      { name: 'Web Landing', device: 'web', type: 'saas-redesign' },
      { name: 'Mobile Portfolio', device: 'mobile', type: 'portfolio-mobile' },
      { name: 'Audit Report', device: 'web', type: 'portfolio-audit' },
    ],
    conversations: [
      { q: '帮我做一个高端 AI 产品的落地页', a: '触发需求推断引擎，设定 VARIANCE=8 / MOTION=7 / DENSITY=3，生成深色高端风落地页，含动态 Hero、Bento 特性网格、客户证言和 CTA。', output: 'AI 落地页 · 深色高端 · 动效丰富' },
      { q: '审查一下我的作品集网站', a: '运行 Anti-Slop Audit Panel，检测 AI 模板痕迹（紫色渐变、三栏卡片、Inter 字体等），输出审计报告和逐项修复建议。', output: '审计报告 · 12 项问题 · 修复方案' },
      { q: '帮我做一个高端厨具品牌的电商网站', a: '推断品牌调性为 Cold Luxury 方向，使用银灰 + 铬 + 烟雾配色，避免米色+黄铜的 AI 默认配色，生成高端电商体验。', output: '厨具电商 · Cold Luxury · 高端质感' },
      { q: '这个模态框的交互有问题，帮我修', a: '分析模态框的打开/关闭动效、背景模糊、焦点管理、键盘操作，修复动效曲线和可访问性问题。', output: '模态框修复 · 动效优化 · 焦点管理' },
      { q: '我要做一个 Awwwards 级别的创意 agency 网站', a: '设定 VARIANCE=10 / MOTION=9 / DENSITY=3，使用滚动驱动动画、kinetic typography、自定义光标，生成实验性创意网站。', output: '创意 agency · Awwwards 级 · 实验性动效' },
    ],
    prompts: [
      { title: '高端落地页', text: '使用 Taste Skill 帮我设计一个高端 AI 产品的落地页，要求深色主题、动态 Hero、Bento 网格、精致动效，避免 AI 模板感。' },
      { title: '设计审计', text: '用 Taste Skill 的 Anti-Slop Audit Panel 审查我的网站设计，检测所有 AI 模板痕迹，按严重程度输出审计报告和修复建议。' },
      { title: '品牌电商', text: '使用 Taste Skill 为我的高端厨具品牌设计电商网站，要求 Cold Luxury 风格，避免米色+黄铜的常见配色，突出产品质感。' },
      { title: '交互修复', text: '用 Taste Skill 审查并修复我网站上的模态框交互问题，包括动效曲线、背景模糊、焦点管理、键盘可访问性。' },
      { title: '创意网站', text: '使用 Taste Skill 帮我做一个 Awwwards 级别的创意 agency 网站，要求滚动驱动动画、动态排版、实验性交互，VARIANCE 拉满。' },
    ],
    userReviews: {
      rating: 4.9, count: 850,
      summary: 'Taste Skill 是一个反廉价感前端设计技能，通过三旋钮系统和需求推断引擎，帮助 AI 生成摆脱模板感的高质量界面设计。',
      pros: ['反廉价感审计非常精准', '三旋钮系统直观易用', '需求推断引擎节省时间', '字体层级校准专业', '动效控制细致入微', '配色一致性锁定有效', '设计品味明显提升', '输出质量稳定'],
      cons: ['对简单页面可能过度设计', '三旋钮需要学习成本', '部分预设不够丰富', '对非英语需求推断稍弱', '生成速度较慢'],
      articles: [
        { title: 'Taste-Skill v2 深度解析：12 项硬核升级，让 AI 网页告别塑料感', source: 'CSDN', url: 'https://blog.csdn.net/gitblog_00067/article/details/159430285' },
        { title: 'Taste Skill Frontend Framework: Teaching AI Agents Design Judgment', source: 'Hamster', url: 'https://tryhamster.com/methods/taste-skill-frontend-design-framework' },
        { title: 'Taste-Skill: Stop Accepting Boring AI Frontend Output', source: 'PromptHub', url: 'https://prompts.brightcoding.dev/blog/taste-skill-stop-accepting-boring-ai-frontend-output' },
        { title: 'design-taste-frontend — Agent Skills Marketplace', source: 'agskills.dev', url: 'https://agskills.dev/leonxlnx/taste-skill/design-taste-frontend' },
        { title: 'Taste Skill 体验：专治AI前端廉价感', source: '小红书', url: 'https://www.xiaohongshu.com/search_result?keyword=Taste%20Skill%20%E5%89%8D%E7%AB%AF%E8%AE%BE%E8%AE%A1', platform: 'xiaohongshu' },
        { title: '82.6k星的Taste Skill，如何让AI设计有品味', source: '微信公众号', url: 'https://weixin.sogou.com/weixin?type=2&query=Taste%20Skill%20%E8%AE%BE%E8%AE%A1%E5%93%81%E5%91%B3', platform: 'wechat' }],
    },
  },
  {
    id: 'impeccable',
    outputType: 'html',
    author: 'pbakaus',
    addedDate: '2026-08-25',
    name: 'Impeccable',
    category: '设计质量检测',
    github: 'https://github.com/pbakaus/impeccable',
    website: 'https://impeccable.style',
    stars: 64765,
    version: 'v4.1.3',
    updated: '2026-08',
    triggerSummary: '当你需要 AI 帮你做前端设计质量控制时就调用它 —— 23 个设计命令（craft/audit/critique/polish/bolder/quieter 等）+ 60 条确定性检测规则，支持 15+ AI 编程工具，一键安装后通过 /impeccable 命令使用，专注消除 AI 生成的模板感设计。',

    workflow: [
      { step: 1, title: '安装到 AI 编程工具', desc: '一键安装到 Claude Code、Cursor、Windsurf、Copilot 等 15+ AI 编程工具' },
      { step: 2, title: '选择设计命令', desc: '从 23 个设计命令中选择：craft（创作）、audit（审计）、critique（批评）、polish（打磨）、bolder（更大胆）、quieter（更克制）等' },
      { step: 3, title: '运行 60 条检测规则', desc: '执行 60 条确定性检测规则，覆盖间距、对齐、层级、对比度、字体、图标、动效等维度' },
      { step: 4, title: '识别 AI 模板感', desc: '专门检测 AI 生成设计的模板感问题，如千篇一律的渐变、圆角、阴影和布局' },
      { step: 5, title: '实时浏览器迭代', desc: '在真实浏览器中实时预览和迭代，边改边看效果，不依赖静态截图' },
      { step: 6, title: '输出质量报告', desc: '生成最终设计质量报告，列出问题清单、修复建议和改进前后对比' },
    ],    officialIntro: 'Impeccable 是为 AI 编程助手提供的设计指导技能。1 个技能、23 个命令、实时浏览器迭代，以及 59 条针对 AI 生成前端设计的确定性检测规则。从 Anthropic 的 frontend-design 发展而来，通过扩展的技能和 7 个领域特定参考文件，与 AI 生成设计的反模式（Inter 字体、紫色渐变、卡片嵌套卡片、彩色背景上的灰色文字等）做斗争。CLI 和浏览器扩展可以在没有 LLM 和 API 密钥的情况下运行确定性规则。覆盖网站、落地页、仪表盘、产品 UI、应用外壳、组件、表单、设置、引导和空状态。',
    suitableFor: [
      { type: '已有项目设计优化', desc: '先审计再修复，不重写整个项目' },
      { type: '企业官网升级改版', desc: '59 条确定性规则，质量可量化' },
      { type: 'SaaS 产品 UI 打磨', desc: '23 个设计命令，精准定位问题' },
      { type: '电商网站体验优化', desc: '反 AI 模板感，提升品牌独特性' },
      { type: '移动端 APP 界面改进', desc: '实时浏览器迭代，所见即所得' },
      { type: '设计系统规范化', desc: '确定性检测规则，统一输出标准' },
    ],
    plainDesc: '你已经有一个网站或项目，但设计质量参差不齐、有很多 AI 模板感的问题时就用它。它不会帮你从零做设计，而是先审计问题，再用 60 条确定性规则（不是靠 AI 感觉）逐个修复，适合已有项目需要提升设计质量、消除"AI 味"的场景。',
    capabilities: ['23个设计命令', '60条确定性检测规则', '反AI模板检测', '实时浏览器迭代', '多工具支持(15+)', '设计钩子自动检测'],
    components: [
      { name: 'craft', desc: '完整的 shape-then-build 流程，含视觉迭代', type: 'ds-generator' },
      { name: 'audit', desc: '技术质量检测：可访问性、性能、响应式', type: 'audit-panel' },
      { name: 'critique', desc: 'UX 设计评审：层级、清晰度、情感共鸣', type: 'a11y' },
      { name: 'polish', desc: '最终打磨：设计系统对齐、交付就绪检查', type: 'typography' },
      { name: 'detect CLI', desc: '独立 CLI 工具，无需 LLM 即可检测 60 条规则', type: 'grid' },
    ],
    examples: [
      { name: 'Neo Mirai 案例研究', desc: '真实项目使用 Impeccable 命令前后对比', type: 'saas-redesign' },
      { name: 'AI Slop 检测', desc: '自动识别 Inter 字体、紫色渐变、卡片嵌套等 AI 模板特征', type: 'portfolio-audit' },
    ],
    pageDemos: [
      { name: 'Web Audit', device: 'web', type: 'portfolio-audit' },
      { name: 'Design System', device: 'web', type: 'saas-redesign' },
      { name: 'Mobile Polish', device: 'mobile', type: 'mobile-portfolio' },
    ],
    conversations: [
      { q: '帮我审计这个落地页的设计质量', a: '使用 /impeccable audit landing 运行技术质量检测，60 条确定性规则自动扫描可访问性、性能、响应式问题，输出问题清单和修复建议。', output: '审计报告 · 60条规则 · 修复建议' },
      { q: '我的页面看起来很无聊，帮我增强设计感', a: '使用 /impeccable bolder 放大设计表现力，打破 AI 模板感：替换过度使用的字体、增加战略色彩、优化视觉层级和动效。', output: '设计增强 · 反模板 · 视觉层级' },
      { q: '帮我做最终交付前的打磨', a: '使用 /impeccable polish 进行最终检查：设计系统对齐、间距节奏统一、交互状态完整、交付就绪确认。', output: '最终打磨 · 设计系统对齐 · 交付就绪' },
      { q: '这个页面的 UX 有问题，帮我评审', a: '使用 /impeccable critique 进行 UX 设计评审：分析信息层级、清晰度、情感共鸣，输出结构化评审报告。', output: 'UX评审 · 信息层级 · 情感共鸣' },
      { q: '帮我初始化项目的设计上下文', a: '使用 /impeccable init 进行一次性设置：选择品牌/产品方向，生成 PRODUCT.md 和 DESIGN.md，配置实时模式，后续命令自动读取设计上下文。', output: '设计初始化 · PRODUCT.md · DESIGN.md' },
    ],
    prompts: [
      { title: '设计质量审计', text: '使用 /impeccable audit 审计我的整个网站，检测所有可访问性、性能、响应式问题，按严重程度排序并给出修复代码。' },
      { title: '反AI模板增强', text: '我的页面有典型的 AI 模板感（Inter字体、紫色渐变、卡片嵌套），用 /impeccable bolder 帮我彻底改造，让设计看起来更独特、更有品味。' },
      { title: '最终交付打磨', text: '用 /impeccable polish 对我的项目进行最终交付前的全面打磨，包括设计系统对齐、间距节奏统一、交互状态补全、性能优化。' },
      { title: 'UX设计评审', text: '用 /impeccable critique 对我的产品页面进行深度 UX 评审，分析信息层级、用户流程、情感共鸣，输出结构化的评审报告和改进建议。' },
      { title: '项目设计初始化', text: '用 /impeccable init 初始化我的项目设计上下文，选择产品方向，生成完整的 PRODUCT.md 和 DESIGN.md，配置设计钩子和实时模式。' },
    ],
    userReviews: {
      rating: 4.7, count: 3200,
      summary: 'Impeccable 是目前最全面的 AI 前端设计质量控制 skill，23 个设计命令 + 60 条确定性检测规则，支持 15+ AI 编程工具，从 Anthropic 的 frontend-design 发展而来，专注于消除 AI 生成的模板感设计。',
      pros: ['60条确定性检测规则无需LLM', '23个设计命令覆盖全流程', '支持15+AI编程工具', '反AI模板检测精准', '实时浏览器迭代模式', '设计钩子自动检测', 'CLI工具可独立运行', '文档完善案例丰富'],
      cons: ['初始配置有学习成本', '部分命令需要图像生成能力', '钩子配置在部分工具需手动授权', '规则覆盖以Web为主', '大型项目检测速度较慢'],
      articles: [
        { title: 'Impeccable:为AI注入设计思维，提升前端界面质量', source: '51CTO', url: 'https://blog.51cto.com/u_16213600/14570937' },
        { title: 'Impeccable Review 2026', source: 'AI Tools Atlas', url: 'https://aitoolsatlas.ai/tools/impeccable/review' },
        { title: 'a design language for AI agents with anti-slop rules', source: 'ghtrends.dev', url: 'https://ghtrends.dev/pbakaus/impeccable/' },
        { title: 'Impeccable: The Design Language That Makes AI Better at Design', source: 'PyShine', url: 'https://pyshine.com/Impeccable-Design-Language-for-AI/' },
        { title: 'Impeccable 实测：AI生成UI的质检神器', source: '小红书', url: 'https://www.xiaohongshu.com/search_result?keyword=Impeccable%20AI%20UI%E8%AE%BE%E8%AE%A1', platform: 'xiaohongshu' },
        { title: '41条确定性规则，Impeccable如何反AI模板感', source: '微信公众号', url: 'https://weixin.sogou.com/weixin?type=2&query=Impeccable%20%E5%8F%8DAI%E6%A8%A1%E6%9D%BF%E6%84%9F', platform: 'wechat' }],
    },
  },

  {
    id: 'remotion',
    outputType: 'html',
    author: 'remotion-dev',
    addedDate: '2026-08-28',
    name: 'Remotion',
    category: '前端工具',
    github: 'https://github.com/remotion-dev/remotion',
    website: 'https://www.remotion.dev',
    stars: 58057,
    version: 'v4.0.520',
    updated: '2026-06',
    triggerSummary: '用React代码创作视频，适合批量生成营销视频、数据可视化动画、产品演示',
    officialIntro: 'Remotion is a framework for creating videos programmatically using React. Video tools for the agent era. Make videos agentically, interactively, or programmatically — React Code is the source of truth. Switch your workflow at any point.',
    plainDesc: '用写React代码的方式做视频，不用PR、不用剪映。前端工程师用熟悉的技术栈就能做视频，特别适合需要批量生成视频、数据可视化动画、产品演示的场景。',
    capabilities: [
      '编程式视频创作 — 用React组件定义每一帧画面',
      'Agent视频生成 — 配合AI编码代理自动生成视频',
      '交互式编辑 — Studio拖拽编辑动画时间线',
      '批量渲染 — 数据驱动批量生成百万级个性化视频',
      '设计系统 — 创建可复用的动画资产库',
      '多端渲染 — 支持Node.js/Lambda/Vercel/客户端渲染',
    ],
    components: [
      'Composition — 定义视频尺寸、帧率、时长',
      'Sequence — 精确控制时间线序列',
      'AbsoluteFill — 全屏填充容器组件',
      'useCurrentFrame — 获取当前帧的Hook',
      'spring() — 物理弹性动画函数',
    ],
    examples: [
      'GitHub Unwrapped — 个性化年度回顾视频，数据驱动生成',
      'Fireship "This video was made with code" — 纯代码生成视频演示',
    ],
    suitableFor: [
      { type: '视频编辑平台', desc: '在线视频编辑器、动画制作工具、动态图形设计平台' },
      { type: '内容创作SaaS', desc: '营销视频批量生成、社交媒体内容自动化、广告视频工厂' },
      { type: '数据可视化平台', desc: '数据驱动的动态图表视频、实时数据报告动画、仪表盘录屏' },
      { type: '产品演示工具', desc: '产品功能演示动画、教程视频自动生成、SaaS onboarding视频' },
      { type: '教育平台', desc: '课程动画制作、知识点讲解视频、互动教学内容生成' },
      { type: '企业品牌工具', desc: '品牌动画资产库、企业宣传视频模板系统、活动视频批量生成' },
    ],
    workflow: [
      { step: 1, title: '项目初始化', desc: '运行 npx create-video@latest 创建Remotion项目，选择模板或空白项目' },
      { step: 2, title: '定义Composition', desc: '设置视频的宽度、高度、帧率(fps)、总时长(durationInFrames)' },
      { step: 3, title: '编写React组件', desc: '用useCurrentFrame获取当前帧，结合CSS/SVG/Canvas/WebGL定义动画效果' },
      { step: 4, title: '预览调试', desc: '用Remotion Studio实时预览视频，调整时间线、参数和动画曲线' },
      { step: 5, title: '渲染输出', desc: '调用renderMedia()或CLI命令，通过Chrome Headless+FFmpeg渲染为MP4/WebM' },
      { step: 6, title: '部署自动化', desc: '部署到Lambda/Vercel/自有服务器，实现数据驱动的批量视频渲染管线' },
    ],
    pageDemos: [
      { type: 'landing', title: '视频创作平台官网', desc: '展示Remotion能力的营销落地页' },
      { type: 'dashboard', title: '视频渲染管理后台', desc: '批量视频任务管理和渲染状态监控' },
      { type: 'mobile-app', title: '移动端视频编辑器', desc: '手机端视频创作和预览界面' },
    ],
    conversations: [
      { q: '帮我做一个产品发布的宣传视频', a: '使用Remotion创建Composition，用Sequence组织开场、产品展示、CTA三个段落，spring()做元素入场动画', output: '生成30秒产品宣传视频React代码' },
      { q: '如何用数据批量生成1000个个性化视频？', a: '用renderMedia()循环遍历数据集，每条数据作为inputProps传入组件，Lambda并行渲染', output: '批量渲染脚本和数据驱动组件' },
      { q: '做一个数据可视化的动态图表视频', a: '用recharts或d3结合useCurrentFrame，让柱状图/折线图随帧增长，添加数字计数动画', output: '数据可视化动画视频组件' },
      { q: '视频里的文字怎么加打字机效果？', a: '用useCurrentFrame计算当前应显示的字符数，slice()截取文本，配合光标闪烁动画', output: '打字机效果文字组件' },
      { q: '怎么把Remotion集成到我的SaaS产品里？', a: '用@remotion/player嵌入播放器，后端用Lambda渲染，用户自定义参数后触发生成', output: 'SaaS视频生成集成方案代码' },
    ],
    prompts: [
      { title: '产品宣传视频', text: '用Remotion创建一个30秒的SaaS产品宣传视频，包含品牌开场、3个核心功能展示、用户评价、CTA结尾，使用现代简约设计风格' },
      { title: '数据可视化动画', text: '创建一个数据可视化视频，展示年度销售数据增长，包含动态柱状图、折线图、数字计数动画，时长20秒' },
      { title: '教程讲解视频', text: '制作一个编程教程的开场视频，包含标题动画、目录展示、讲师介绍，使用科技感深色主题' },
      { title: '社交媒体短视频', text: '生成一个15秒的Instagram Reels视频，竖屏9:16，包含产品图片轮播、价格标签、行动号召，适合电商营销' },
      { title: '品牌动画Logo', text: '创建一个5秒的品牌Logo动画，包含粒子汇聚效果、文字渐入、弹性缩放，输出透明背景WebM' },
    ],
    userReviews: {
      rating: 4.7,
      count: 1280,
      summary: 'Remotion是视频即代码领域的标杆项目，51k+ stars证明了其受欢迎程度。前端工程师可以用熟悉的React技术栈创作视频，特别适合批量生成和数据驱动场景。学习曲线平缓，但复杂动画仍需深入理解帧编程模型。商业使用需注意公司许可要求。',
      pros: [
        '用React写视频，前端工程师零学习成本上手',
        '视频即代码，可版本控制、可复用、可自动化',
        '数据驱动批量渲染，适合个性化视频生成',
        '支持CSS/SVG/Canvas/WebGL，视觉表现力强',
        'Remotion Studio实时预览，调试体验好',
        '活跃的社区生态，628+ releases持续更新',
        '多端渲染支持，Lambda/Vercel/Node.js均可',
        'AI Agent友好，配合Codex/Claude自动生成视频',
      ],
      cons: [
        '商业使用需公司许可（4人以上团队）',
        '复杂动画需要理解帧编程模型，有学习曲线',
        '渲染依赖Chrome Headless，服务器资源消耗较大',
        '相比专业视频软件，视觉特效能力有限',
        '音频处理功能相对基础',
      ],
      articles: [
        { title: 'Remotion 深度解析:用 React 写视频，前端工程师的 After Effects 替代方案', source: '博客园', url: 'https://www.cnblogs.com/jzssuanfa/p/20492813' },
        { title: '以前做视频靠时间，现在做视频靠提示词——Codex+Remotion体验记', source: 'CSDN', url: 'https://blog.csdn.net/weixin_74888502/article/details/162003231' },
        { title: 'Remotion Review: Features, Pros & Cons and how it compares to alternatives', source: 'Websites2Know', url: 'https://websites2know.com/remotion-review/' },
        { title: '使用 Remotion 打造专业级产品动画视频', source: 'CSDN', url: 'https://blog.csdn.net/u010475928/article/details/160267142' },
        { title: 'remotion:用 React 组件以代码方式生成视频', source: 'X-CMD', url: 'https://cn.x-cmd.com/install/remotion/' },
      ],
    },
  },
  {
    id: 'awesome-design-md-jp',
    outputType: 'html',
    author: 'kzhrknt',
    addedDate: '2026-09-01',
    name: 'Awesome Design MD JP',
    category: '综合设计系统',
    github: 'https://github.com/kzhrknt/awesome-design-md-jp',
    website: 'https://github.com/kzhrknt/awesome-design-md-jp',
    stars: 949,
    version: 'v1.0.0',
    updated: '2026-08',
    triggerSummary: '当你需要 AI 生成准确的日本语 UI 时就调用它 —— 480+ 日本网站设计规范，含 CJK 排版、禁则处理、和文フォントチェーン',
    officialIntro: 'A curated collection of DESIGN.md files for Japanese web services — enabling AI agents to generate accurate Japanese UI with proper typography, font stacks, and typographic rules.',
    plainDesc: '这是一个日本网站设计规范的大合集。简单说，就是把 Apple、MUJI、Mercari 这些日本知名网站的设计风格、字体、颜色、排版规则都整理成了 AI 能读懂的 DESIGN.md 文件。你要做日本语网站时，把对应的 DESIGN.md 给 AI，它就能生成符合日本网站风格的 UI，不会出现字体不对、行间距太窄、标点符号跑到行首这种问题。',
    capabilities: [
      '480+ 日本网站设计规范',
      'CJK 排版规则（禁則処理）',
      '和文フォントフォールバックチェーン',
      'OpenType プロポーショナル組版',
      '混植ルール（和文+欧文）',
      'デザイントークン可視化プレビュー',
    ],
    components: [
      'DESIGN.md テンプレート',
      'preview.html ショーケース',
      'gallery.html ギャラリー',
      'デザイントークン抽出スクリプト',
      'CJK タイポグラフィ規約',
    ],
    examples: [
      { title: 'Apple Japan デザインシステム', desc: 'Apple 日本公式サイトの DESIGN.md' },
      { title: 'MUJI 無印良品 デザイン', desc: '無印良品公式サイトの DESIGN.md' },
    ],
    suitableFor: [
      { type: '日本語 EC サイト', desc: 'メルカリ・楽天・Amazon JP 风格の电商网站' },
      { type: '日本語コーポレートサイト', desc: '伊藤忠・リクルート・ソニー风格の企业官网' },
      { type: '日本語メディア/ブログ', desc: 'はてな・note・Zenn风格の媒体网站' },
      { type: '日本語 SaaS ダッシュボード', desc: 'freee・マネーフォワード风格の管理画面' },
      { type: '日本語モバイルアプリ', desc: 'PayPay・LINE・メルカリ风格の移动端 UI' },
      { type: '多言語対応サイト', desc: '日英双语或多语言网站' },
    ],
    pageDemos: [
      { type: 'ecommerce-brand', title: '日本語 EC サイト', desc: 'Mercari 风格二手电商平台，含商品列表、详情、购物车' },
      { type: 'landing', title: '日本語コーポレートサイト', desc: '索尼风格企业官网，含产品展示、技术介绍、招聘信息' },
      { type: 'mobile-app', title: '日本語モバイルアプリ', desc: 'PayPay 风格支付应用，含首页、账单、个人中心' },
    ],
    conversations: [
      { q: '帮我做一个日本二手电商平台的首页', a: '已生成 Mercari 风格 UI，应用了 CJK 排版规则和和文フォントチェーン', output: 'Mercari 风格电商首页，含商品瀑布流、搜索栏、分类导航' },
      { q: '这个日本网站的字体不对，怎么修复？', a: '已应用和文フォントフォールバックチェーン：Hiragino Kaku Gothic ProN → Noto Sans JP → sans-serif', output: '字体修复后的页面，日本语显示正常' },
      { q: '帮我检查日本语排版的禁则处理', a: '已检查：句読点が行頭に来ない、記号の前後スペース、ルビの位置', output: '禁则处理检查报告，标注了3处需要修复的排版问题' },
      { q: '做一个日本 SaaS 管理后台', a: '已生成 freee 风格管理画面，应用了日本语表格排版和表单规范', output: 'freee 风格 SaaS 仪表盘，含数据表格、图表、侧边导航' },
      { q: '日本企业官网的设计规范是什么？', a: '已提取索尼、伊藤忠、Recruit 等企业官网的 DESIGN.md，含配色、字体、布局规范', output: '日本企业官网设计规范汇总文档' },
    ],
    prompts: [
      { title: '日本电商平台首页', text: '创建一个日本二手电商平台首页，参考 Mercari 风格，应用 CJK 排版规则和和文フォントチェーン，包含商品瀑布流、搜索栏、分类导航、底部 Tab' },
      { title: '日本企业官网', text: '创建一个日本科技企业官网，参考索尼风格，包含产品展示、技术介绍、新闻动态、招聘信息、联系表单，应用日本语排版规范' },
      { title: '日本支付应用', text: '创建一个日本移动支付应用界面，参考 PayPay 风格，包含首页、扫码支付、账单、个人中心，应用日本语表单和按钮规范' },
      { title: '日本 SaaS 管理后台', text: '创建一个日本 SaaS 管理后台，参考 freee 风格，包含数据仪表盘、表格、图表、侧边导航，应用日本语数据表格排版规范' },
      { title: '日本媒体博客', text: '创建一个日本技术媒体博客，参考 Zenn/はてな风格，包含文章列表、详情页、标签、作者信息，应用日本语文章排版规范' },
    ],
    workflow: [
      { step: 1, title: '対象サイト選択', desc: '从 480+ 日本网站中选择与目标项目最接近的 DESIGN.md' },
      { step: 2, title: 'DESIGN.md 読み込み', desc: '读取对应的 DESIGN.md 文件，提取品牌色、字体、排版规则' },
      { step: 3, title: 'デザイントークン抽出', desc: '从 DESIGN.md 中提取设计令牌，转换为 CSS 变量或 Tailwind 配置' },
      { step: 4, title: 'CJK タイポグラフィ適用', desc: '应用日本语排版规则：禁则处理、字间距、行间距、和文フォントチェーン' },
      { step: 5, title: 'UI 生成', desc: '基于设计规范生成 UI 组件和页面，确保风格一致' },
      { step: 6, title: '品質チェック', desc: '检查日本语排版质量：禁则处理、字体回退、行间距、混植规则' },
    ],
    articles: [
      { title: 'awesome-design-md-jp：日本語UI DESIGN.md集', source: 'AI Heartland', url: 'https://ai-heartland.com/agent/awesome-design-md-jp/' },
      { title: 'AI時代のデザインシステム「DESIGN.md」入門', source: 'エレファンキューブ', url: 'https://www.elephancube.co.jp/2026/04/design-md/' },
      { title: 'Design.mdとは何か、使い方は？', source: 'Banani', url: 'https://www.banani.co/ja/blog/design-md-guide' },
      { title: 'DESIGN.md という新しいフォーマットの衝撃', source: 'unType', url: 'https://www.untype.jp/blog/design-systems-design-md-format' },
    ],
    userReviews: {
      rating: 4.5,
      count: 320,
      summary: 'Awesome Design MD JP 是日本语 UI 设计规范的权威合集，480+ 日本知名网站的 DESIGN.md 文件覆盖电商、企业、媒体、SaaS 等全场景。最大价值在于解决了 AI 生成日本语 UI 时的排版痛点——禁则处理、和文フォントチェーン、行间距、混植规则等。对于需要做日本市场的产品团队，这是不可或缺的参考资源。',
      pros: [
        '480+ 日本知名网站设计规范，覆盖全行业场景',
        '完整的 CJK 排版规则，解决 AI 生成日本语 UI 的排版痛点',
        '和文フォントフォールバックチェーン，确保字体显示正确',
        '每个 DESIGN.md 都有 preview.html 可视化预览',
        '持续更新，每月新增多个网站的设计规范',
        '基于 Google Stitch 提唱的 DESIGN.md 标准格式',
        'AI Agent 友好，可直接作为上下文输入生成 UI',
        '开源免费，MIT 许可，可商业使用',
      ],
      cons: [
        '仅覆盖日本网站，不包含其他 CJK 语言（中文、韩文）',
        '设计规范是静态提取，可能与网站最新设计有偏差',
        '需要手动选择对应的 DESIGN.md，没有智能推荐功能',
        '部分网站的规范可能不够详细，缺少组件级设计',
        '对于非日本市场的产品，参考价值有限',
      ],
      articles: [
        { title: 'awesome-design-md-jp：日本語UI DESIGN.md集', source: 'AI Heartland', url: 'https://ai-heartland.com/agent/awesome-design-md-jp/' },
        { title: 'AI時代のデザインシステム「DESIGN.md」入門', source: 'エレファンキューブ', url: 'https://www.elephancube.co.jp/2026/04/design-md/' },
        { title: 'Design.mdとは何か、使い方は？', source: 'Banani', url: 'https://www.banani.co/ja/blog/design-md-guide' },
      ],
    },
  },
  {
    id: 'oh-my-cover-design',
    outputType: 'image',
    previewFormat: 'png',
    previewRatio: '3:4',
    author: 'hongfamonvAI',
    addedDate: '2026-09-02',
    name: 'Oh My Cover Design',
    category: '封面设计工具',
    github: 'https://github.com/hongfamonvAI/oh-my-cover-design',
    website: '',
    stars: 227,
    version: 'v1.0.0',
    updated: '2026-05',
    triggerSummary: '当你需要 AI 自动生成小红书爆款封面时就调用它 —— 把文章扔给 agent，它读完内容、问你几个问题，然后输出可以直接跑图的封面提示词，支持10种构图风格。',
    workflow: [
      { step: 1, title: '输入文章内容', desc: '把文章或主题发给 agent，skill 自动触发，开始分析内容调性和目标受众。' },
      { step: 2, title: '选择构图风格', desc: 'agent 会问你选择哪种构图风格：深色渐变风、纯色扁平风、产品主视觉风、对比卡片风、极简留白风等10种。' },
      { step: 3, title: '确认视觉元素', desc: 'agent 依次询问：有没有人脸参考图、人物表情、有没有产品截图要放进去、背景色调、字体偏好。' },
      { step: 4, title: '生成封面提示词', desc: '问完所有问题后，agent 输出一段完整的、可以直接跑图的封面提示词，标题自动帮你想，构图逻辑全内置。' },
      { step: 5, title: '跑图生成封面', desc: '把提示词复制到图像生成工具（如 Midjourney、DALL-E、豆包文生图），生成 1080x1440 小红书封面。' },
      { step: 6, title: '调整优化', desc: '如果不满意，可以告诉 agent 调整方向（换风格、换色调、换标题），agent 重新生成提示词。' },
    ],
    officialIntro: '把文章扔给 agent，它读完内容、问你几个问题，然后输出一段可以直接跑图的封面提示词。标题自动帮你想，构图逻辑全内置好了。支持 Claude Code、Codex，以及任何支持自定义 skill 的 AI agent。',
    suitableFor: [
      { type: '小红书封面', desc: '小红书笔记封面，1080x1440 竖版，大字标题+人物/产品' },
      { type: '公众号头图', desc: '微信公众号文章头图，2.35:1 横版，品牌感强' },
      { type: '短视频封面', desc: '抖音/B站视频封面，16:9 横版，冲击力强' },
      { type: '知识付费海报', desc: '课程/训练营宣传海报，信息层级清晰，转化导向' },
      { type: '产品主视觉', desc: '产品发布主视觉图，产品截图+卖点文字' },
      { type: '对比测评图', desc: '前后对比/好坏对比类内容，对比卡片风专用' },
    ],
    plainDesc: '这是一个帮你自动生成小红书封面提示词的工具。简单说，你把文章内容发给 AI，它会问你几个问题（选什么风格、要不要人物、什么色调），然后直接给你一段可以复制去跑图的提示词。不需要懂设计，不需要自己写提示词，10种构图风格随便选，标题都帮你想好了。',
    capabilities: [
      '10种构图风格内置',
      '文章内容自动分析',
      '标题自动生成',
      '交互式问题引导',
      '多平台尺寸适配',
      '提示词一键复制',
    ],
    components: [
      '深色渐变风构图',
      '纯色扁平风构图',
      '产品主视觉风构图',
      '对比卡片风构图',
      '极简留白风构图',
    ],
    examples: [
      'AI工具测评文章 → 深色渐变风封面，人物居中，大字"双面特工"压在后面',
      '设计工具教程 → 产品主视觉风封面，UI截图占主体，标题"再见了Figma"',
    ],
    conversations: [
      { q: '帮我生成一篇关于AI编程工具的小红书封面', a: '好的！我来帮你生成封面提示词。首先请选择构图风格：1.深色渐变风 2.纯色扁平风 3.产品主视觉风 4.对比卡片风 5.极简留白风 6.海报拼贴风 7.人物侧置留白风 8.背影构图风 9.局部出镜风 10.正面对视风' },
      { q: '选深色渐变风', a: '好的，深色渐变风。接下来请问：有没有人脸参考图？如果有，请描述人物特征（性别、年龄、表情、穿着）。如果没有，我会用通用人物描述。' },
      { q: '没有人脸，用产品截图', a: '好的，用产品截图。请问产品截图是什么内容？（如：代码编辑器界面、软件主界面、工具操作演示）另外，背景色调偏好？（深蓝、深紫、深红、纯黑）' },
      { q: '代码编辑器，深蓝色', a: '好的，信息收集完毕。正在生成封面提示词...\n\n【标题】双面特工\n【提示词】A dramatic Xiaohongshu cover design, dark blue gradient background from #0a1628 to #1e3a5f, a cute red robot character floating in center with mechanical arms holding various tech icons (email, calendar, bug, lock), large bold white Chinese text "双面特工" at top and bottom, cinematic lighting, 3D render style, high contrast, 1080x1440 vertical format, trending on Xiaohongshu\n\n复制以上提示词到图像生成工具即可！' },
      { q: '标题换一个，更有冲击力', a: '好的，换一个更有冲击力的标题。\n\n【新标题】一个人顶一个团队\n【更新提示词】...（标题部分替换为"一个人顶一个团队"，其他保持不变）\n\n需要调整其他部分吗？' },
    ],
    prompts: [
      { title: '深色渐变风-人物居中', text: 'A dramatic Xiaohongshu cover design, dark purple gradient background, young woman with surprised expression in center, large bold white Chinese title at top, tech icons floating around, cinematic lighting, 3D render, 1080x1440' },
      { title: '产品主视觉风-截图主体', text: 'A clean product-focused Xiaohongshu cover, dark blue gradient background, large software UI screenshot in center taking 60% of space, bold white Chinese title at top, subtle glow effect, modern tech aesthetic, 1080x1440' },
      { title: '对比卡片风-前后对比', text: 'A comparison-style Xiaohongshu cover, split screen design, left side showing messy/bad design with red tint, right side showing clean/good design with green tint, VS text in middle, bold title at top, 1080x1440' },
      { title: '极简留白风-标题唯一焦点', text: 'A minimalist Xiaohongshu cover, pure white background, large elegant black Chinese title in center taking 40% of space, tiny subtle decorative element in corner, lots of whitespace, premium editorial style, 1080x1440' },
      { title: '海报拼贴风-多层叠加', text: 'A collage-style Xiaohongshu cover, multiple layered elements including photos, text blocks, geometric shapes, tape effects, vintage paper texture, bold title overlapping images, dynamic composition, 1080x1440' },
    ],
    userReviews: {
      rating: 4.7,
      count: 89,
      summary: '小红书创作者的封面神器，10种构图风格覆盖绝大多数场景，交互式提问降低了使用门槛，不需要懂设计也能生成专业封面提示词。',
      pros: [
        '10种构图风格内置，覆盖绝大多数小红书场景',
        '交互式提问引导，不需要懂设计也能用',
        '标题自动生成，解决了"不知道起什么标题"的痛点',
        '提示词可以直接复制跑图，无需二次修改',
        '支持 Claude Code、Codex 等多种 agent 平台',
        '文章内容自动分析，调性匹配准确',
        '多平台尺寸适配（小红书/公众号/短视频）',
        '开源免费，持续更新构图风格',
      ],
      cons: [
        '目前只支持生成提示词，不能直接生成图片',
        '需要配合外部图像生成工具使用',
        '人物描述需要用户自己提供，没有人物库',
        '部分构图风格的提示词模板比较固定',
        '没有封面效果预览功能',
      ],
      articles: [
        { title: 'Oh My Cover Design：小红书封面提示词自动生成工具', source: 'GitHub', url: 'https://github.com/hongfamonvAI/oh-my-cover-design' },
        { title: '10种小红书封面构图风格详解', source: '技术博客', url: 'https://github.com/hongfamonvAI/oh-my-cover-design#10-种构图风格' },
        { title: 'AI Agent 自动生成爆款封面的实践', source: '小红书', url: 'https://www.xiaohongshu.com/search_result?keyword=oh%20my%20cover%20design' },
      ],
    },
  },


  {
    id: 'travel-memory-sticker-card',
    name: 'Travel Memory Sticker Card',
    author: 'carolinaaafy',
    addedDate: '2026-09-02',
    github: 'https://github.com/carolinaaafy/travel-memory-sticker-card',
    website: '',
    stars: 396,
    watchers: 0,
    forks: 32,
    version: 'v1.0.0',
    category: '图片生成类',
    outputType: 'image',
    previewFormat: 'png',
    previewRatio: '3:2',
    updated: '2026-08',
    triggerSummary: '把旅行/街景/风景/肖像/宠物照片变成 3:2 横向文艺记忆贴纸卡片',
    officialIntro: 'A Codex skill for turning travel photos into collectible memory sticker cards. Transform a user-uploaded photograph into one horizontal collectible memory card with a large quiet editorial illustration, six integrated journaling-sticker motifs, three small English keywords beneath the left illustration, tactile paper grain, and deliberately clumsy flat color fields.',
    plainDesc: '这是一个帮你把照片变成文艺记忆贴纸卡片的工具。你上传一张旅行或生活照片，它会重绘成 3:2 横向的明信片风格卡片：左边是大幅水粉剪纸插画，底部有3个英文关键词，右边是6个从照片里提取的小贴纸，整体是复古印刷的纸质感。适合做旅行纪念、手账素材、小红书配图。',
    suitableFor: [
      { type: '旅行纪念卡', desc: '把旅行照片变成可收藏的 3:2 横向记忆卡片' },
      { type: '手账素材', desc: '生成6个主题贴纸和插画，适合手账拼贴' },
      { type: '社交媒体配图', desc: '小红书/Instagram 文艺风格封面和配图' },
      { type: '明信片设计', desc: '个性化明信片制作，可打印收藏' },
      { type: '宠物肖像纪念', desc: '宠物照片的艺术化重绘，保留识别特征' },
      { type: '街景风景艺术化', desc: '城市街景和自然风光的水粉剪纸风格处理' }
    ],
    capabilities: [
      '照片艺术化重绘 — 转换为水粉剪纸风格插画',
      '记忆卡片生成 — 3:2 横向可收藏卡片布局',
      '智能贴纸提取 — 从源图像自动提取6个主题贴纸',
      '关键词生成 — 自动生成3个场景相关英文关键词',
      '纸质质感模拟 — 统一纸纹、手切边缘、复古印刷效果',
      '地标识别保留 — 智能识别并保留关键地标文字'
    ],
    components: [
      '主插画区 — 左侧 66-68% 大幅无框插画',
      '关键词页脚 — 底部3个英文关键词，点分隔',
      '贴纸列 — 右侧 30-32% 6个模切贴纸',
      '纸质边框 — 4-5% 暖白色外边距',
      '风格渲染引擎 — 水粉/剪纸/risograph 统一质感'
    ],
    examples: [
      { title: '粉伞街角记忆卡', desc: '日本街景照片转换为粉色雨伞主题卡片' },
      { title: '雪地巴士记忆卡', desc: '冬季雪景照片转换为复古巴士主题卡片' }
    ],
    workflow: [
      { step: 1, title: '检查源图像', desc: '详细查看上传的照片，识别场景结构和细节' },
      { step: 2, title: '识别核心元素', desc: '确定情感中心、主导空间姿态、一个紧凑识别锚点' },
      { step: 3, title: '决定地标文字', desc: '判断是否保留源图像中的地标文字（默认不保留）' },
      { step: 4, title: '选择贴纸和关键词', desc: '选6个源图像衍生贴纸图案和3个简洁英文关键词' },
      { step: 5, title: '生成记忆卡片', desc: '按风格规范从源照片生成 3:2 横向卡片' },
      { step: 6, title: '质量检查', desc: '检查贴纸数量、关键词、风格一致性，必要时重新生成' }
    ],
    pageDemos: [
      { type: 'landing', title: '旅行纪念卡生成器', desc: '上传照片生成记忆卡片的落地页' },
      { type: 'portfolio-audit', title: '手账素材库', desc: '贴纸卡片作品集展示页' },
      { type: 'mobile-app', title: '旅行记忆 APP', desc: '手机端照片转卡片应用' }
    ],
    conversations: [
      { q: '帮我把这张京都旅行照片变成记忆卡片', a: '好的，我来分析这张照片，提取鸟居、石板路、日式建筑等元素，生成一张 3:2 横向记忆卡片，包含6个主题贴纸和3个英文关键词。', output: '生成一张京都主题记忆贴纸卡片' },
      { q: '这张宠物照片可以做成卡片吗', a: '可以！我会保留宠物的识别特征，把背景简化为大块色块，提取宠物玩具、食盆等元素作为贴纸，生成一张温馨的宠物纪念卡。', output: '生成宠物主题记忆卡片' },
      { q: '我想要街景风格的卡片', a: '好的，街景照片特别适合这个风格。我会把建筑简化为几何色块，提取路灯、招牌、自行车等元素作为贴纸，整体用低饱和度的复古色调。', output: '生成城市街景记忆卡片' },
      { q: '卡片上可以保留地标名称吗', a: '可以，但只保留一个真正能定位记忆的地标文字，比如"京都"或"Tokyo Tower"。普通广告、菜单、价格牌都会被抽象掉。', output: '生成带地标文字的记忆卡片' },
      { q: '这个卡片能打印吗', a: '可以！3:2 横向比例适合打印成明信片或照片。输出是高分辨率位图，纸纹质感在印刷后效果更好。', output: '生成可打印的高分辨率记忆卡片' }
    ],
    prompts: [
      { title: '京都旅行纪念卡', text: '把这张京都伏见稻荷大社的照片变成记忆卡片，保留千本鸟居的识别特征' },
      { title: '海边度假记忆卡', text: '把这张冲绳海边照片变成记忆卡片，提取海浪、礁石、遮阳伞作为贴纸' },
      { title: '城市街景卡片', text: '把这张东京涩谷街头照片变成记忆卡片，低饱和度复古色调' },
      { title: '宠物纪念卡', text: '把这张猫咪照片变成记忆卡片，保留猫咪的识别特征，温馨色调' },
      { title: '雪山风景卡', text: '把这张北海道雪景照片变成记忆卡片，提取雪山、缆车、松树作为贴纸' }
    ],
    userReviews: {
      rating: 4.5,
      count: 128,
      summary: '独特的水粉剪纸记忆卡片风格，贴纸系统和关键词设计让照片变成可收藏的艺术品，手账爱好者和旅行博主的必备工具。',
      pros: [
        '独特的水粉剪纸风格，辨识度极高',
        '3:2 横向卡片布局，适合打印和收藏',
        '自动提取6个主题贴纸，手账友好',
        '3个英文关键词增加文艺感',
        '统一纸质质感，复古印刷效果',
        '智能保留地标文字，记忆点清晰',
        '支持旅行/街景/风景/肖像/宠物多种场景',
        '输出质量稳定，风格一致性强'
      ],
      cons: [
        '仅支持 3:2 横向比例，灵活性有限',
        '个人非商业使用许可，商用需授权',
        '依赖图像生成工具，无法纯代码实现',
        '贴纸数量固定为6个，不可自定义',
        '关键词仅支持英文，不支持中文'
      ],
      articles: [
        { title: 'Travel Memory Sticker Card - GitHub 官方仓库', url: 'https://github.com/carolinaaafy/travel-memory-sticker-card', platform: 'github' },
        { title: 'carolinaaafy 的小红书主页', url: 'https://www.xiaohongshu.com/user/profile/carolinaaafy', platform: 'xiaohongshu' },
        { title: 'Codex Skill 生态：图片生成类 Skill 盘点', url: 'https://github.com/topics/codex-skill', platform: 'github' }
      ]
    }
  },
];
