const skills = [
  {
    id: 'shadcn-ui',
    name: 'shadcn/ui',
    category: '综合组件库',
    github: 'https://github.com/shadcn-ui/ui',
    website: 'https://ui.shadcn.com',
    stars: 121871,
    version: 'v4.19.0',
    updated: '2026-08',
    triggerSummary: '当你用 React + Tailwind 做项目需要 UI 组件时就调用它 —— 不是 npm 安装，而是把组件源码直接复制到你项目里，完全可控、可定制。',

    workflow: [
      { step: 1, title: '初始化项目', desc: '创建 React + TypeScript + Tailwind CSS 项目，配置路径别名和 Tailwind 主题' },
      { step: 2, title: '安装 shadcn/ui', desc: '运行 CLI 命令初始化，选择框架（Next.js/Vite/Remix）、基础颜色和 CSS 变量' },
      { step: 3, title: '选择所需组件', desc: '从组件库中选择需要的组件（Button、Card、Dialog、Form、Table等），CLI 自动复制源码' },
      { step: 4, title: '定制组件样式', desc: '修改组件源码中的 Tailwind 类名，调整配色、间距、圆角等，完全不受组件库限制' },
      { step: 5, title: '组合构建页面', desc: '将多个组件组合成完整页面，配合 React 状态管理实现交互逻辑' },
      { step: 6, title: '主题与暗色模式', desc: '配置 CSS 变量实现主题切换，支持亮色/暗色模式和品牌色定制' },
    ],    officialIntro: 'shadcn/ui 是一套可访问、可定制的组件集合，你可以直接复制粘贴到自己的应用中。免费、开源，用于构建你自己的组件库。基于 TypeScript、Tailwind CSS 和 Radix UI 原语构建，支持 Next.js、Vite、Remix、Astro 等多种框架，提供 CLI 工具安装和管理组件，以及注册表系统发布和分发代码。',
    suitableFor: [
      { type: 'SaaS 产品后台', desc: '组件丰富，表单/表格/导航齐全' },
      { type: '企业管理系统', desc: '可控性强，易于深度定制扩展' },
      { type: '数据仪表盘', desc: '配合图表库，适合数据密集型界面' },
      { type: '开发者工具', desc: '技术风格，文档/控制台/API 管理' },
      { type: '电商商家后台', desc: '订单/商品/用户管理等复杂表单' },
      { type: 'CRM/ERP 系统', desc: '中后台场景，组件可组合性强' },
    ],
    plainDesc: '你用 React + Tailwind 做项目，需要按钮、卡片、弹窗这些 UI 组件时就用它。跟其他组件库不一样，它不是 npm 安装，而是把组件源码直接复制到你项目里，想怎么改就怎么改，完全不受组件库限制。',
    capabilities: ['组件源码复制', 'Tailwind 样式系统', 'Radix UI 原语', '主题定制', '可访问性', 'TypeScript 支持'],
    components: [
      { name: 'Button', desc: '多种变体和尺寸的按钮组件', type: 'button' },
      { name: 'Card', desc: '灵活的内容卡片容器', type: 'card' },
      { name: 'Dialog', desc: '模态对话框，支持嵌套和表单', type: 'dialog' },
      { name: 'Dropdown Menu', desc: '下拉菜单，支持分组和快捷方式', type: 'dropdown' },
      { name: 'Form', desc: '基于 React Hook Form 的表单组件', type: 'form' },
    ],
    examples: [
      { name: 'Dashboard 仪表盘', desc: '数据看板布局，含侧边栏、统计卡片、图表区域', type: 'dashboard' },
      { name: 'Landing Page 落地页', desc: '营销落地页，含 Hero、特性网格、定价、CTA', type: 'landing' },
    ],
    pageDemos: [
      { name: 'Web Dashboard', device: 'web', type: 'dashboard' },
      { name: 'Mobile App', device: 'mobile', type: 'mobile-app' },
      { name: 'Landing Page', device: 'web', type: 'landing' },
    ],
    conversations: [
      { q: '帮我做一个 SaaS 产品的定价页面', a: '使用 shadcn/ui 的 Card、Button、Badge 组件构建三档定价卡片，含月度/年度切换、特性对比列表和 CTA 按钮。', output: '定价页 · 3 档方案 · 年付优惠' },
      { q: '需要一个用户设置页面', a: '使用 Tabs 组织设置分类，配合 Input、Switch、Select 表单组件，底部放置保存按钮。', output: '设置页 · 5 个分类 · 表单验证' },
      { q: '做一个数据表格页面', a: '使用 Table 组件配合 Pagination、Badge 状态标签，支持列排序和行选择。', output: '表格页 · 排序 · 分页 · 批量操作' },
      { q: '帮我构建一个登录注册页面', a: '使用 Card 容器包裹表单，Input + Label 组合，Button 提交，底部链接切换登录/注册。', output: '认证页 · 登录/注册切换 · 表单校验' },
      { q: '需要一个通知中心组件', a: '使用 Dropdown Menu 触发通知列表，每条通知含 Avatar、标题、时间、未读标记。', output: '通知中心 · 未读标记 · 批量已读' },
    ],
    prompts: [
      { title: '构建组件库页面', text: '使用 shadcn/ui 帮我构建一个组件库展示页面，包含 Button、Card、Dialog、Form 组件的用法示例和代码片段。' },
      { title: 'SaaS 仪表盘', text: '用 shadcn/ui 做一个 SaaS 产品的管理后台仪表盘，需要侧边栏导航、统计卡片、数据表格和图表区域。' },
      { title: '电商产品页', text: '使用 shadcn/ui 组件构建一个电商产品详情页，包含产品图片轮播、规格选择、加入购物车按钮和用户评价区域。' },
      { title: '任务管理应用', text: '用 shadcn/ui 做一个任务管理应用界面，需要看板视图、任务卡片、拖拽排序、筛选和搜索功能。' },
      { title: '文档网站', text: '使用 shadcn/ui 构建一个技术文档网站，包含侧边栏目录、内容区域、代码高亮、搜索框和上一页/下一页导航。' },
    ],
    userReviews: {
      rating: 4.8, count: 1240,
      summary: 'shadcn/ui 是目前最受欢迎的 React 组件库之一，以"复制源码而非安装"的理念著称，深度整合 Tailwind CSS 和 Radix UI。',
      pros: ['完全可控的组件源码', '与 Tailwind CSS 无缝集成', '基于 Radix UI 的可访问性', '活跃的社区和持续更新', '支持主题定制和暗色模式', 'TypeScript 类型完善', '组件覆盖全面', '文档质量高'],
      cons: ['需要手动管理组件版本', '首次配置有一定门槛', '部分复杂组件需自行扩展', '不适合非 Tailwind 项目', '组件样式需自行统一'],
      articles: [
        { title: 'shadcn/ui 官方文档 — 组件与主题定制', source: 'ui.shadcn.com', url: 'https://ui.shadcn.com/docs' },
        { title: 'Major Update: Base UI & Radix UI Support with Shadcn Styles', source: 'Shadcn Studio', url: 'https://shadcnstudio.com/blog/major-update-base-ui-radix-ui-support/' },
        { title: 'The AI-Native shadcn/ui Component Library for React', source: 'shadcn.io', url: 'https://www.shadcn.io/' },
        { title: 'shadcn/ui Cheatsheet — 42+ 组件速查', source: 'GitHub', url: 'https://github.com/shadcnstore/shadcn-cheatsheet/' },
      ,
        { title: 'shadcn/ui 实战：从0搭建企业级组件库', source: '小红书', url: 'https://www.xiaohongshu.com/search_result?keyword=shadcn%2Fui%20%E5%AE%9E%E6%88%98', platform: 'xiaohongshu' },
        { title: '深度解析 shadcn/ui 为什么成为 AI 生成默认选择', source: '微信公众号', url: 'https://weixin.sogou.com/weixin?type=2&query=shadcn%2Fui%20%E6%B7%B1%E5%BA%A6%E8%A7%A3%E6%9E%90', platform: 'wechat' }],
    },
  },
  {
    id: 'ui-ux-pro-max',
    name: 'UI/UX Pro Max',
    category: '综合设计系统',
    github: 'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill',
    website: 'https://ui-ux-pro-max-skill.nextlevelbuilder.io/',
    stars: 101000,
    version: 'v2.15.0',
    updated: '2026-07',
    triggerSummary: '当你需要 AI 帮你做 UI/UX 设计时就调用它 —— 不管是从零做页面、选配色字体、审查现有界面、修交互 bug，还是优化响应式和无障碍。',

    workflow: [
      { step: 1, title: '分析项目需求', desc: '理解产品定位、目标用户、核心功能和品牌调性，确定设计方向' },
      { step: 2, title: '生成设计系统', desc: '智能设计系统生成器分析需求，几秒内生成完整的定制化设计系统（配色/字体/组件规范）' },
      { step: 3, title: '选择风格方向', desc: '从 79 种可搜索风格、192 种产品配色、74 种字体搭配中选择最匹配的方案' },
      { step: 4, title: '生成页面与组件', desc: '基于设计系统生成页面布局、UI 组件和交互模式，支持 22 种技术栈' },
      { step: 5, title: 'UX 与可访问性审查', desc: '应用 119 条 UX 指南，审查用户体验、响应式布局和无障碍标准' },
      { step: 6, title: '动效与图表优化', desc: '选择 17 个 GSAP 动效预设和 25 种图表类型，提升页面表现力和数据可视化' },
    ],    officialIntro: 'UI/UX Pro Max 是一个为跨多平台和框架构建专业 UI/UX 提供设计智能的 AI 技能。它将结构化的设计知识——精选的 CSV 数据、参考文档和 Python 生成脚本——安装到 AI 编程助手中（Claude Code、Cursor、Windsurf、Copilot 等约 10 种工具），使助手能够开箱即用地生成生产级 UI。v2.0 旗舰特性是智能设计系统生成器，分析项目需求并在几秒钟内生成完整的定制化设计系统。包含 79 种可搜索风格、192 种产品配色、74 种字体搭配、119 条 UX 指南、105 个图标、17 个 GSAP 预设、25 种图表类型和 22 种技术栈。',
    suitableFor: [
      { type: '品牌官网/企业官网', desc: '多风格可选，品牌识别度强' },
      { type: '产品落地页', desc: '79 种风格，营销转化导向设计' },
      { type: '电商网站/品牌商城', desc: '192 种产品配色，商品展示优化' },
      { type: '个人作品集', desc: '创意风格丰富，视觉冲击力强' },
      { type: '营销活动页/专题页', desc: '快速生成，多主题适配' },
      { type: '移动端 APP', desc: 'iOS/Android 跨平台设计规范' },
    ],
    plainDesc: '你要做一个网站或 APP，但不知道怎么设计才好看时就用它。它会从零开始帮你定配色、选字体、排布局，生成一套完整的设计系统和页面，适合完全没有设计思路、需要 AI 从头帮你做的场景。',
    capabilities: ['设计系统生成', '配色方案', '字体层级', '响应式布局', '可访问性审计', '交互原型'],
    components: [
      { name: 'Design System Generator', desc: '一键生成完整设计令牌和组件规范', type: 'ds-generator' },
      { name: 'Color Palette Builder', desc: '智能配色方案生成器，支持对比度检测', type: 'color-builder' },
      { name: 'Typography Scale', desc: '字体层级系统，含字号、行高、字重', type: 'typography' },
      { name: 'Responsive Grid', desc: '响应式网格布局系统', type: 'grid' },
      { name: 'A11y Audit Panel', desc: '可访问性审计面板，WCAG 标准检测', type: 'a11y' },
    ],
    examples: [
      { name: '金融科技 Dashboard', desc: '深色主题数据看板，含实时行情、交易面板、持仓图表', type: 'fintech-dashboard' },
      { name: '电商品牌官网', desc: '高端电商品牌站，含产品展示、品牌故事、购物流程', type: 'ecommerce-brand' },
    ],
    pageDemos: [
      { name: 'Web Dashboard', device: 'web', type: 'fintech-dashboard' },
      { name: 'Mobile Banking', device: 'mobile', type: 'mobile-banking' },
      { name: 'Brand Landing', device: 'web', type: 'ecommerce-brand' },
    ],
    conversations: [
      { q: '帮我从零设计一个金融 App 的界面', a: '使用 UI/UX Pro Max 生成金融科技设计系统，深色主题 + 数据可视化组件，输出完整的页面流程和交互规范。', output: '金融 App · 12 个页面 · 深色主题' },
      { q: '我的网站配色很丑，帮我重新选', a: '分析品牌调性后生成 3 套配色方案，每套含主色、辅助色、中性色、语义色，并标注 WCAG 对比度。', output: '3 套配色 · 对比度检测 · 使用规范' },
      { q: '审查一下这个页面的可访问性', a: '运行 A11y Audit Panel，检测对比度、键盘导航、屏幕阅读器标签、焦点状态，输出问题清单和修复建议。', output: '审计报告 · 17 项问题 · 修复建议' },
      { q: '帮我做一套响应式布局规范', a: '生成 6 档断点的响应式网格系统，含容器宽度、列数、间距、排版缩放规则，适配手机到超宽屏。', output: '响应式规范 · 6 档断点 · 网格系统' },
      { q: '这个按钮的交互体验不好，帮我优化', a: '分析按钮的状态流转（默认/悬停/按下/加载/禁用），优化动效曲线和反馈时机，输出完整的交互规范。', output: '按钮交互 · 5 种状态 · 动效规范' },
    ],
    prompts: [
      { title: '生成设计系统', text: '使用 UI/UX Pro Max 为我的 SaaS 产品生成一套完整的设计系统，包括配色、字体、间距、圆角、阴影、组件规范。' },
      { title: '配色方案优化', text: '我的品牌主色是 #4F46E5，用 UI/UX Pro Max 帮我生成一套完整的配色方案，包含辅助色、中性色、语义色，并确保 WCAG AA 对比度。' },
      { title: '可访问性审计', text: '用 UI/UX Pro Max 的 A11y Audit Panel 审计我的网站，检测所有可访问性问题，按严重程度排序并给出修复代码。' },
      { title: '响应式布局', text: '使用 UI/UX Pro Max 帮我设计一套从手机到 4K 屏幕的响应式布局规范，包含断点、网格、排版缩放和组件适配规则。' },
      { title: '交互原型', text: '用 UI/UX Pro Max 为我的移动应用设计一套完整的交互原型，包含页面流转、手势操作、动效规范和状态管理。' },
    ],
    userReviews: {
      rating: 4.6, count: 680,
      summary: 'UI/UX Pro Max 是一个综合性的 AI 设计系统技能，覆盖从设计令牌生成到可访问性审计的全流程，适合需要系统化设计能力的团队。',
      pros: ['设计系统覆盖全面', '配色方案智能且合规', '可访问性审计实用', '响应式规范详细', '交互设计有深度', '输出可直接落地'],
      cons: ['学习曲线较陡', '部分功能需配合其他工具', '生成结果需人工微调', '文档不够完善', '对非设计背景用户不够友好'],
      articles: [
        { title: 'UI/UX Pro Max 官方文档 — 67 种 UI 风格与设计系统生成', source: 'nextlevelbuilder.io', url: 'https://ui-ux-pro-max-skill.nextlevelbuilder.io/' },
        { title: 'ui-ux-pro-max-skill — LangLabs 技能详情页', source: 'LangLabs', url: 'https://langlabs.io/nextlevelbuilder/ui-ux-pro-max-skill' },
        { title: 'UI UX Pro Max — GitHub README (含 v2.0 设计系统生成器)', source: 'GitHub', url: 'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill' },
      ,
        { title: 'UI/UX Pro Max 实测：AI设计神器还是噱头？', source: '小红书', url: 'https://www.xiaohongshu.com/search_result?keyword=UI%2FUX%20Pro%20Max%20%E5%AE%9E%E6%B5%8B', platform: 'xiaohongshu' },
        { title: '192种配色+79种风格，这个AI设计skill太强了', source: '微信公众号', url: 'https://weixin.sogou.com/weixin?type=2&query=UI%2FUX%20Pro%20Max%20%E9%85%8D%E8%89%B2%20%E9%A3%8E%E6%A0%BC', platform: 'wechat' }],
    },
  },
  {
    id: 'taste-skill',
    name: 'Taste Skill',
    category: '设计品味审计',
    github: 'https://github.com/Leonxlnx/taste-skill',
    website: 'https://www.tasteskill.dev',
    stars: 82600,
    version: 'v2.0.0',
    updated: '2026-08',
    subSkills: [
      { name: 'taste-skill', installName: 'design-taste-frontend', category: '实现类', familyColor: 'blue', subtitle: '上下文驱动 · 全能适配', plainDesc: 'Taste 家族的主力。你要从零做落地页、作品集、产品官网时用它，它会读需求、定风格、输出完整代码。', steps: ['读需求（Brief Inference）', '定三旋钮 8/6/4（按需求覆盖）', '映射设计系统 or 诚实标注美学', '从 14 章规则里"按需取用"', '60+ 项 Pre-Flight 机械检查'],
        prompt: '创建一个高端创意工作室的落地页，包含Hero区域、服务介绍、作品集展示、客户评价和联系表单。要求设计感强、排版精致、动效流畅。',
        model: '豆包 2.1 Turbo + design-taste-frontend skill v2.1',
        projectType: '高端创意工作室落地页'
      },
      { name: 'taste-skill-v1', installName: 'design-taste-frontend-v1', category: '实现类', familyColor: 'blue', subtitle: '原版保留 · 精确回退', plainDesc: 'Taste 的旧版本。之前项目用 v1，升级 v2 后行为不对时用它回退，保证行为一致。', steps: ['依赖 v1 精确行为的项目使用', 'v2 默认版不兼容时回退', '保留 v1 全部规则和旋钮', '不引入 v2 新特性', '稳定输出，行为可预测'],
        prompt: '创建一个SaaS产品官网，包含Hero、功能特性、定价方案、客户评价和FAQ。使用v1版本的设计规则。',
        model: '豆包 2.1 Turbo + design-taste-frontend skill v1.0',
        projectType: 'SaaS产品官网'
      },
      { name: 'gpt-tasteskill', installName: 'gpt-taste', category: '实现类', familyColor: 'blue', subtitle: '强制随机化 · Awwwards 单流派', plainDesc: 'Taste 的"激进版"。想要 Awwwards 那种大胆、有创意、动效强的设计时用它，随机化选元素避免千篇一律。', steps: ['用 prompt 长度做随机种子', '"掷骰子"选 hero/字体/组件/GSAP', '套 AIDA 骨架（Attention→Action）', '强制 GSAP 高动效（禁静态）', '输出前 自证清单'],
        prompt: '创建一个Awwwards级别的创意 agency 网站，要求大胆的实验性布局、强烈的视觉冲击、GSAP高级动效、随机化的元素选择。',
        model: '豆包 2.1 Turbo + gpt-taste skill（强制随机化 + GSAP高动效）',
        projectType: '创意Agency网站（Awwwards风格）'
      },
      { name: 'soft-skill', installName: 'high-end-visual-design', category: '实现类', familyColor: 'green', subtitle: '柔和对比 · 大量留白 · 昂贵感', plainDesc: '想要"很贵"的设计感时用它。柔和配色、大量留白、高级字体、弹簧动效，适合高端品牌、奢侈品、创意工作室。', steps: ['柔和对比配色（低饱和高级色）', '大量留白营造呼吸感', '高级字体选择和层级', '弹簧动效（Spring Physics）', '细节打磨到像素级'],
        prompt: '创建一个奢侈品牌官网，包含产品展示、品牌故事、精品店定位和会员专区。要求柔和对比、大量留白、高级字体、弹簧动效。',
        model: '豆包 2.1 Turbo + high-end-visual-design skill（高端代理风格）',
        projectType: '奢侈品牌官网'
      },
      { name: 'minimalist-skill', installName: 'minimalist-ui', category: '实现类', familyColor: 'green', subtitle: 'Notion/Linear 风格 · 编辑级界面', plainDesc: '喜欢 Notion、Linear 那种极简、干净、克制的界面时用它。中性配色、清晰结构，适合工具类、SaaS 产品。', steps: ['克制配色（中性色为主）', '清晰结构和信息层级', '编辑级产品界面标准', '极简交互和微动效', '内容优先，装饰最少'],
        prompt: '创建一个Notion/Linear风格的项目管理工具界面，包含侧边栏导航、任务列表、看板视图、统计面板。要求极简、干净、克制。',
        model: '豆包 2.1 Turbo + minimalist-ui skill（编辑级界面标准）',
        projectType: '项目管理SaaS工具界面'
      },
      { name: 'brutalist-skill', installName: 'industrial-brutalist-ui', category: '实现类', familyColor: 'green', subtitle: '瑞士排版 · 强对比 · 硬核机械感', plainDesc: '想要硬核、个性、有冲击力的设计时用它。瑞士排版、强对比、实验性布局，适合音乐、潮流、科技品牌。', steps: ['瑞士排版网格系统', '强对比配色（黑白+强调色）', '实验性布局和不对称', '粗野字体和大字号', '硬核机械感视觉语言'],
        prompt: '创建一个独立音乐厂牌的官网，要求瑞士排版网格、强对比黑白配色、实验性不对称布局、粗野大字号、硬核机械感。',
        model: '豆包 2.1 Turbo + industrial-brutalist-ui skill（瑞士排版+粗野主义）',
        projectType: '独立音乐厂牌官网'
      },
      { name: 'stitch-skill', installName: 'stitch-design-taste', category: '实现类', familyColor: 'green', subtitle: 'Google Stitch 兼容 · DESIGN.md 导出', plainDesc: '用 Google Stitch（谷歌的 AI 编程工具）做项目时用它。生成 Stitch 能直接读取的 DESIGN.md 设计规范文件。', steps: ['适配 Google Stitch 工作流', '生成 DESIGN.md 设计规范文件', '包含配色、字体、组件规范', 'Stitch 可直接读取使用', '保持 taste-skill 设计标准'],
        prompt: '创建一个Google Stitch兼容的设计系统文档页面，输出DESIGN.md格式，包含设计令牌、组件规范、布局原则。',
        model: '豆包 2.1 Turbo + stitch-design-taste skill（DESIGN.md导出）',
        projectType: '设计系统文档页'
      },
      { name: 'redesign-skill', installName: 'redesign-existing-projects', category: '实现类', familyColor: 'orange', subtitle: '先审计 → 再定点修复，不重写', plainDesc: '已有项目但设计很丑想改版时用它。不重写整个项目，先审计问题，再定点修复布局、间距、样式。', steps: ['审计现有 UI 问题清单', '定位布局、间距、层级问题', '修复样式和交互 bug', '保留原有功能和结构', '输出前后对比和修改说明'],
        prompt: '对一个现有的企业官网进行改版升级，先审计现有设计的问题，然后定点修复导航、Hero、卡片排版和响应式，不重写整个项目。',
        model: '豆包 2.1 Turbo + redesign-existing-projects skill（审计→定点修复）',
        projectType: '企业官网改版升级'
      },
      { name: 'image-to-code-skill', installName: 'image-to-code', category: '实现类', familyColor: 'purple', subtitle: '图→分析→代码管线', plainDesc: '你有一张设计图/参考图，想变成真实前端代码时用它。先分析图的设计语言，再写出匹配的代码。', steps: ['先生成参考图（视觉锚点）', '分析设计语言和布局结构', '提取配色、字体、间距规范', '实现匹配的前端代码', '对照原图校验还原度'],
        prompt: '分析一张高端电商产品页的设计图，提取布局结构、配色方案、字体层级、组件样式，然后输出完整的HTML/CSS代码实现。',
        model: '豆包 2.1 Turbo + image-to-code skill（图→分析→代码管线）',
        projectType: '设计图转代码（电商产品页）'
      },
      { name: 'imagegen-frontend-web', installName: 'imagegen-frontend-web', category: '图像生成类', familyColor: 'purple', subtitle: '网页逐 section 出图 · 反廉价感', plainDesc: '不想写代码，只想先看网站长什么样时用它。生成网页设计参考图（Hero、落地页、多区块），拿图再给编码 AI 实现。', steps: ['Hero 区域设计图生成', '落地页多区块连续出图', '强排版和视觉层次', '反廉价感艺术指导', '输出高保真设计参考图'],
        prompt: '生成一个高端餐厅官网的网页设计参考图，按section逐段输出：导航栏、Hero、菜单展示、餐厅环境、预订区域、页脚。',
        model: '豆包 2.1 Turbo + imagegen-frontend-web skill（网页逐section出图）',
        projectType: '高端餐厅官网设计图'
      },
      { name: 'imagegen-frontend-mobile', installName: 'imagegen-frontend-mobile', category: '图像生成类', familyColor: 'purple', subtitle: '移动端屏幕流 · iOS/Android', plainDesc: '要做手机 APP，想先看界面长什么样时用它。生成 iOS/Android 设计参考图和多屏流程图。', steps: ['iOS/Android/跨平台适配', 'mockup 场景图生成', '可读字体和触控友好布局', '连贯屏幕组（多屏流程）', '输出移动端设计参考图'],
        prompt: '生成一个健身追踪App的移动端屏幕流设计图，包含：启动页、首页仪表盘、运动记录、数据统计、个人中心，共5个屏幕。',
        model: '豆包 2.1 Turbo + imagegen-frontend-mobile skill（移动端屏幕流）',
        projectType: '健身App移动端设计图'
      },
      { name: 'brandkit', installName: 'brandkit', category: '图像生成类', familyColor: 'purple', subtitle: '品牌设计板 · 跨品类身份', plainDesc: '做新品牌，需要 Logo 方向、配色、字体、品牌视觉时用它。生成一套完整的品牌设计板。', steps: ['Logo 方向探索', '配色系统定义', '字体选择和搭配', '跨品类身份应用', '输出完整品牌设计板'],
        prompt: '生成一个新消费品牌的完整品牌套件图，包含：Logo设计、品牌配色系统、字体规范、名片设计、社交媒体模板、包装设计。',
        model: '豆包 2.1 Turbo + brandkit skill（品牌套件生成）',
        projectType: '新消费品牌VI套件'
      },
      { name: 'output-skill', installName: 'full-output-enforcement', category: '实现类', familyColor: 'amber', subtitle: '强制完整输出 · 禁占位符', plainDesc: 'AI 写代码总写一半就停、或用"// TODO"占位时用它。强制输出完整代码，不允许省略和占位。', steps: ['检测模型输出是否半成品', '强制完整代码（不省略）', '禁止占位注释（如 // TODO）', '补全被截断的部分', '输出前完整性自检'],
        prompt: '创建一个完整的多页面Web应用，强制输出完整代码，禁止使用占位符、省略号或"此处省略"。包含：登录页、仪表盘、列表页、详情页、设置页。',
        model: '豆包 2.1 Turbo + full-output-enforcement skill（强制完整输出）',
        projectType: '多页面Web应用（完整输出）'
      },
    ],
    familyStructure: {
      title: 'taste-skill 家族 · UI 技能全景',
      subtitle: '13 个技能 = 4 类 UI 技能 + 1 个辅助技能（full-output-enforcement 非 UI）',
      categories: [
        { name: '通用主控型', tagline: '从零做落地页/作品集', workflow: '读需求 → 定旋钮 → 出代码', color: 'blue', skills: [
          { name: 'design-taste-frontend', note: 'v2 主技能，最全' },
          { name: 'design-taste-frontend-v1', note: '旧版，精简' },
          { name: 'gpt-taste', note: '更严格变体，强 GSAP' },
        ]},
        { name: '既定风格型', tagline: '方向已定，只管执行', workflow: '按固定审美体系生成 UI', color: 'green', skills: [
          { name: 'high-end-visual-design', note: '高端代理' },
          { name: 'minimalist-ui', note: '极简编辑风' },
          { name: 'industrial-brutalist-ui', note: '粗野工业风' },
          { name: 'stitch-design-taste', note: '生成 DESIGN.md 给 Google Stitch' },
        ]},
        { name: '存量改版型', tagline: '已有项目升级', workflow: '先审计 → 再定点修复，不重写', color: 'orange', skills: [
          { name: 'redesign-existing-projects', note: '' },
        ]},
        { name: '图片参考型', tagline: '只出图，不出代码', workflow: '生成设计参考图，交给编码 agent', color: 'purple', skills: [
          { name: 'image-to-code', note: '图→分析→代码管线' },
          { name: 'imagegen-frontend-web', note: '网页逐 section 出图' },
          { name: 'imagegen-frontend-mobile', note: '移动端屏幕流' },
          { name: 'brandkit', note: '品牌套件图' },
        ]},
        { name: '辅助型', tagline: '非 UI', workflow: '解决输出截断问题', color: 'amber', skills: [
          { name: 'full-output-enforcement', note: '强制完整输出，禁占位符' },
        ]},
      ],
    },
    triggerSummary: '当你需要 AI 帮你做 UI/UX 设计时就调用它 —— 不管是从零做页面、选配色字体、审查现有界面、修交互 bug，还是优化响应式和无障碍。',

    workflow: [
      { step: 1, title: '读取需求（Brief Inference）', desc: 'AI 自动推断项目需求、目标用户和设计目标，不遗漏关键信息' },
      { step: 2, title: '定三旋钮 8/6/4', desc: '按需求覆盖度调节 Variance（方差）、Motion（动效）、Density（密度）三个核心旋钮' },
      { step: 3, title: '映射设计系统', desc: '映射到现有设计系统，或诚实标注美学选择，不假装是"通用最佳实践"' },
      { step: 4, title: '14 章规则按需取用', desc: '从 14 章设计规则中按需取用，不堆砌全部规则，保持设计的针对性' },
      { step: 5, title: '60+ 项 Pre-Flight 检查', desc: '交付前运行 60+ 项机械检查，确保间距、对齐、层级、对比度等基础质量' },
      { step: 6, title: '反廉价感审计', desc: '自动审计"廉价感"问题，识别模板化设计、渐变滥用、图标不一致等常见 AI 设计缺陷' },
    ],    officialIntro: 'Taste Skill 是一个为 AI 编程助手设计的"设计判断力"技能。它教会 AI 什么是好的设计，通过三个旋钮（Variance 方差 / Motion 动效 / Density 密度）调节设计风格，内置反廉价感审计规则和交付前检查清单，帮助 AI 生成摆脱模板感的高质量界面设计。包含 13 个子技能，覆盖从零做页面、既定风格生成、存量改版、图像参考、完整输出强制等全场景，支持多种 AI 编程工具。',
    suitableFor: [
      { type: '高端品牌官网', desc: '反廉价感审计，设计品质有保障' },
      { type: '创意工作室/设计机构', desc: '13 个子技能，风格多样可定制' },
      { type: '个人作品集', desc: '三旋钮调节，避免千篇一律' },
      { type: 'SaaS 产品营销页', desc: '高动效+强排版，提升转化' },
      { type: '奢侈品/高端消费品牌', desc: '高端视觉子技能，昂贵感营造' },
      { type: '科技创业公司官网', desc: '极简/粗野/高端多风格可选' },
    ],
    plainDesc: '你让 AI 帮你写前端代码，但生成的页面总是很丑、像模板、有"廉价感"时就用它。它会教 AI 什么是好设计，通过三旋钮（方差/动效/密度）调节风格，还会自动审计"廉价感"问题，适合对设计质量有要求、不想做出来的东西千篇一律的场景。',
    capabilities: ['需求推断引擎', '三旋钮设计调节', '反廉价感审计', '字体层级校准', '动效强度控制', '配色一致性锁定'],
    components: [
      { name: 'Design Dial Controller', desc: '三旋钮调节器：Variance / Motion / Density', type: 'dial-controller' },
      { name: 'Brief Inference Card', desc: '需求推断卡片，自动分析设计方向', type: 'brief-inference' },
      { name: 'Anti-Slop Audit Panel', desc: '反廉价感审计面板，检测 AI 模板痕迹', type: 'anti-slop' },
      { name: 'Typography Hierarchy', desc: '字体层级校准器，含字号/行高/字重系统', type: 'typo-hierarchy' },
      { name: 'Motion Preset Selector', desc: '动效强度预设选择器', type: 'motion-preset' },
    ],
    examples: [
      { name: 'SaaS 落地页重设计', desc: '深色高端风，从普通模板到 Awwwards 级别的蜕变', type: 'saas-redesign' },
      { name: '设计师作品集审计', desc: '审计报告风格，逐项标注问题并给出修复方案', type: 'portfolio-audit' },
    ],
    pageDemos: [
      { name: 'Web Landing', device: 'web', type: 'saas-redesign' },
      { name: 'Mobile Portfolio', device: 'mobile', type: 'portfolio-mobile' },
      { name: 'Audit Report', device: 'web', type: 'portfolio-audit' },
    ],
    conversations: [
      { q: '帮我做一个高端 AI 产品的落地页', a: '触发需求推断引擎，设定 VARIANCE=8 / MOTION=7 / DENSITY=3，生成深色高端风落地页，含动态 Hero、Bento 特性网格、客户证言和 CTA。', output: 'AI 落地页 · 深色高端 · 动效丰富' },
      { q: '审查一下我的作品集网站', a: '运行 Anti-Slop Audit Panel，检测 AI 模板痕迹（紫色渐变、三栏卡片、Inter 字体等），输出审计报告和逐项修复建议。', output: '审计报告 · 12 项问题 · 修复方案' },
      { q: '帮我做一个高端厨具品牌的电商网站', a: '推断品牌调性为 Cold Luxury 方向，使用银灰 + 铬 + 烟雾配色，避免米色+黄铜的 AI 默认配色，生成高端电商体验。', output: '厨具电商 · Cold Luxury · 高端质感' },
      { q: '这个模态框的交互有问题，帮我修', a: '分析模态框的打开/关闭动效、背景模糊、焦点管理、键盘操作，修复动效曲线和可访问性问题。', output: '模态框修复 · 动效优化 · 焦点管理' },
      { q: '我要做一个 Awwwards 级别的创意 agency 网站', a: '设定 VARIANCE=10 / MOTION=9 / DENSITY=3，使用滚动驱动动画、kinetic typography、自定义光标，生成实验性创意网站。', output: '创意 agency · Awwwards 级 · 实验性动效' },
    ],
    prompts: [
      { title: '高端落地页', text: '使用 Taste Skill 帮我设计一个高端 AI 产品的落地页，要求深色主题、动态 Hero、Bento 网格、精致动效，避免 AI 模板感。' },
      { title: '设计审计', text: '用 Taste Skill 的 Anti-Slop Audit Panel 审查我的网站设计，检测所有 AI 模板痕迹，按严重程度输出审计报告和修复建议。' },
      { title: '品牌电商', text: '使用 Taste Skill 为我的高端厨具品牌设计电商网站，要求 Cold Luxury 风格，避免米色+黄铜的常见配色，突出产品质感。' },
      { title: '交互修复', text: '用 Taste Skill 审查并修复我网站上的模态框交互问题，包括动效曲线、背景模糊、焦点管理、键盘可访问性。' },
      { title: '创意网站', text: '使用 Taste Skill 帮我做一个 Awwwards 级别的创意 agency 网站，要求滚动驱动动画、动态排版、实验性交互，VARIANCE 拉满。' },
    ],
    userReviews: {
      rating: 4.9, count: 850,
      summary: 'Taste Skill 是一个反廉价感前端设计技能，通过三旋钮系统和需求推断引擎，帮助 AI 生成摆脱模板感的高质量界面设计。',
      pros: ['反廉价感审计非常精准', '三旋钮系统直观易用', '需求推断引擎节省时间', '字体层级校准专业', '动效控制细致入微', '配色一致性锁定有效', '设计品味明显提升', '输出质量稳定'],
      cons: ['对简单页面可能过度设计', '三旋钮需要学习成本', '部分预设不够丰富', '对非英语需求推断稍弱', '生成速度较慢'],
      articles: [
        { title: 'Taste-Skill v2 深度解析：12 项硬核升级，让 AI 网页告别塑料感', source: 'CSDN', url: 'https://blog.csdn.net/gitblog_00067/article/details/159430285' },
        { title: 'Taste Skill Frontend Framework: Teaching AI Agents Design Judgment', source: 'Hamster', url: 'https://tryhamster.com/methods/taste-skill-frontend-design-framework' },
        { title: 'Taste-Skill: Stop Accepting Boring AI Frontend Output', source: 'PromptHub', url: 'https://prompts.brightcoding.dev/blog/taste-skill-stop-accepting-boring-ai-frontend-output' },
        { title: 'design-taste-frontend — Agent Skills Marketplace', source: 'agskills.dev', url: 'https://agskills.dev/leonxlnx/taste-skill/design-taste-frontend' },
      ,
        { title: 'Taste Skill 体验：专治AI前端廉价感', source: '小红书', url: 'https://www.xiaohongshu.com/search_result?keyword=Taste%20Skill%20%E5%89%8D%E7%AB%AF%E8%AE%BE%E8%AE%A1', platform: 'xiaohongshu' },
        { title: '82.6k星的Taste Skill，如何让AI设计有品味', source: '微信公众号', url: 'https://weixin.sogou.com/weixin?type=2&query=Taste%20Skill%20%E8%AE%BE%E8%AE%A1%E5%93%81%E5%91%B3', platform: 'wechat' }],
    },
  },
  {
    id: 'impeccable',
    name: 'Impeccable',
    category: '设计质量检测',
    github: 'https://github.com/pbakaus/impeccable',
    website: 'https://impeccable.style',
    stars: 40000,
    version: 'v4.1.2',
    updated: '2026-08',
    triggerSummary: '当你需要 AI 帮你做前端设计质量控制时就调用它 —— 23 个设计命令（craft/audit/critique/polish/bolder/quieter 等）+ 60 条确定性检测规则，支持 15+ AI 编程工具，一键安装后通过 /impeccable 命令使用，专注消除 AI 生成的模板感设计。',

    workflow: [
      { step: 1, title: '安装到 AI 编程工具', desc: '一键安装到 Claude Code、Cursor、Windsurf、Copilot 等 15+ AI 编程工具' },
      { step: 2, title: '选择设计命令', desc: '从 23 个设计命令中选择：craft（创作）、audit（审计）、critique（批评）、polish（打磨）、bolder（更大胆）、quieter（更克制）等' },
      { step: 3, title: '运行 60 条检测规则', desc: '执行 60 条确定性检测规则，覆盖间距、对齐、层级、对比度、字体、图标、动效等维度' },
      { step: 4, title: '识别 AI 模板感', desc: '专门检测 AI 生成设计的模板感问题，如千篇一律的渐变、圆角、阴影和布局' },
      { step: 5, title: '实时浏览器迭代', desc: '在真实浏览器中实时预览和迭代，边改边看效果，不依赖静态截图' },
      { step: 6, title: '输出质量报告', desc: '生成最终设计质量报告，列出问题清单、修复建议和改进前后对比' },
    ],    officialIntro: 'Impeccable 是为 AI 编程助手提供的设计指导技能。1 个技能、23 个命令、实时浏览器迭代，以及 59 条针对 AI 生成前端设计的确定性检测规则。从 Anthropic 的 frontend-design 发展而来，通过扩展的技能和 7 个领域特定参考文件，与 AI 生成设计的反模式（Inter 字体、紫色渐变、卡片嵌套卡片、彩色背景上的灰色文字等）做斗争。CLI 和浏览器扩展可以在没有 LLM 和 API 密钥的情况下运行确定性规则。覆盖网站、落地页、仪表盘、产品 UI、应用外壳、组件、表单、设置、引导和空状态。',
    suitableFor: [
      { type: '已有项目设计优化', desc: '先审计再修复，不重写整个项目' },
      { type: '企业官网升级改版', desc: '59 条确定性规则，质量可量化' },
      { type: 'SaaS 产品 UI 打磨', desc: '23 个设计命令，精准定位问题' },
      { type: '电商网站体验优化', desc: '反 AI 模板感，提升品牌独特性' },
      { type: '移动端 APP 界面改进', desc: '实时浏览器迭代，所见即所得' },
      { type: '设计系统规范化', desc: '确定性检测规则，统一输出标准' },
    ],
    plainDesc: '你已经有一个网站或项目，但设计质量参差不齐、有很多 AI 模板感的问题时就用它。它不会帮你从零做设计，而是先审计问题，再用 60 条确定性规则（不是靠 AI 感觉）逐个修复，适合已有项目需要提升设计质量、消除"AI 味"的场景。',
    capabilities: ['23个设计命令', '60条确定性检测规则', '反AI模板检测', '实时浏览器迭代', '多工具支持(15+)', '设计钩子自动检测'],
    components: [
      { name: 'craft', desc: '完整的 shape-then-build 流程，含视觉迭代', type: 'ds-generator' },
      { name: 'audit', desc: '技术质量检测：可访问性、性能、响应式', type: 'audit-panel' },
      { name: 'critique', desc: 'UX 设计评审：层级、清晰度、情感共鸣', type: 'a11y' },
      { name: 'polish', desc: '最终打磨：设计系统对齐、交付就绪检查', type: 'typography' },
      { name: 'detect CLI', desc: '独立 CLI 工具，无需 LLM 即可检测 60 条规则', type: 'grid' },
    ],
    examples: [
      { name: 'Neo Mirai 案例研究', desc: '真实项目使用 Impeccable 命令前后对比', type: 'saas-redesign' },
      { name: 'AI Slop 检测', desc: '自动识别 Inter 字体、紫色渐变、卡片嵌套等 AI 模板特征', type: 'portfolio-audit' },
    ],
    pageDemos: [
      { name: 'Web Audit', device: 'web', type: 'portfolio-audit' },
      { name: 'Design System', device: 'web', type: 'saas-redesign' },
      { name: 'Mobile Polish', device: 'mobile', type: 'mobile-portfolio' },
    ],
    conversations: [
      { q: '帮我审计这个落地页的设计质量', a: '使用 /impeccable audit landing 运行技术质量检测，60 条确定性规则自动扫描可访问性、性能、响应式问题，输出问题清单和修复建议。', output: '审计报告 · 60条规则 · 修复建议' },
      { q: '我的页面看起来很无聊，帮我增强设计感', a: '使用 /impeccable bolder 放大设计表现力，打破 AI 模板感：替换过度使用的字体、增加战略色彩、优化视觉层级和动效。', output: '设计增强 · 反模板 · 视觉层级' },
      { q: '帮我做最终交付前的打磨', a: '使用 /impeccable polish 进行最终检查：设计系统对齐、间距节奏统一、交互状态完整、交付就绪确认。', output: '最终打磨 · 设计系统对齐 · 交付就绪' },
      { q: '这个页面的 UX 有问题，帮我评审', a: '使用 /impeccable critique 进行 UX 设计评审：分析信息层级、清晰度、情感共鸣，输出结构化评审报告。', output: 'UX评审 · 信息层级 · 情感共鸣' },
      { q: '帮我初始化项目的设计上下文', a: '使用 /impeccable init 进行一次性设置：选择品牌/产品方向，生成 PRODUCT.md 和 DESIGN.md，配置实时模式，后续命令自动读取设计上下文。', output: '设计初始化 · PRODUCT.md · DESIGN.md' },
    ],
    prompts: [
      { title: '设计质量审计', text: '使用 /impeccable audit 审计我的整个网站，检测所有可访问性、性能、响应式问题，按严重程度排序并给出修复代码。' },
      { title: '反AI模板增强', text: '我的页面有典型的 AI 模板感（Inter字体、紫色渐变、卡片嵌套），用 /impeccable bolder 帮我彻底改造，让设计看起来更独特、更有品味。' },
      { title: '最终交付打磨', text: '用 /impeccable polish 对我的项目进行最终交付前的全面打磨，包括设计系统对齐、间距节奏统一、交互状态补全、性能优化。' },
      { title: 'UX设计评审', text: '用 /impeccable critique 对我的产品页面进行深度 UX 评审，分析信息层级、用户流程、情感共鸣，输出结构化的评审报告和改进建议。' },
      { title: '项目设计初始化', text: '用 /impeccable init 初始化我的项目设计上下文，选择产品方向，生成完整的 PRODUCT.md 和 DESIGN.md，配置设计钩子和实时模式。' },
    ],
    userReviews: {
      rating: 4.7, count: 3200,
      summary: 'Impeccable 是目前最全面的 AI 前端设计质量控制 skill，23 个设计命令 + 60 条确定性检测规则，支持 15+ AI 编程工具，从 Anthropic 的 frontend-design 发展而来，专注于消除 AI 生成的模板感设计。',
      pros: ['60条确定性检测规则无需LLM', '23个设计命令覆盖全流程', '支持15+AI编程工具', '反AI模板检测精准', '实时浏览器迭代模式', '设计钩子自动检测', 'CLI工具可独立运行', '文档完善案例丰富'],
      cons: ['初始配置有学习成本', '部分命令需要图像生成能力', '钩子配置在部分工具需手动授权', '规则覆盖以Web为主', '大型项目检测速度较慢'],
      articles: [
        { title: 'Impeccable:为AI注入设计思维，提升前端界面质量', source: '51CTO', url: 'https://blog.51cto.com/u_16213600/14570937' },
        { title: 'Impeccable Review 2026', source: 'AI Tools Atlas', url: 'https://aitoolsatlas.ai/tools/impeccable/review' },
        { title: 'a design language for AI agents with anti-slop rules', source: 'ghtrends.dev', url: 'https://ghtrends.dev/pbakaus/impeccable/' },
        { title: 'Impeccable: The Design Language That Makes AI Better at Design', source: 'PyShine', url: 'https://pyshine.com/Impeccable-Design-Language-for-AI/' },
      ,
        { title: 'Impeccable 实测：AI生成UI的质检神器', source: '小红书', url: 'https://www.xiaohongshu.com/search_result?keyword=Impeccable%20AI%20UI%E8%AE%BE%E8%AE%A1', platform: 'xiaohongshu' },
        { title: '41条确定性规则，Impeccable如何反AI模板感', source: '微信公众号', url: 'https://weixin.sogou.com/weixin?type=2&query=Impeccable%20%E5%8F%8DAI%E6%A8%A1%E6%9D%BF%E6%84%9F', platform: 'wechat' }],
    },
  },

  {
    id: 'remotion',
    name: 'Remotion',
    category: '前端工具',
    github: 'https://github.com/remotion-dev/remotion',
    website: 'https://www.remotion.dev',
    stars: 57900,
    version: 'v4.0.519',
    updated: '2026-06',
    triggerSummary: '用React代码创作视频，适合批量生成营销视频、数据可视化动画、产品演示',
    officialIntro: 'Remotion is a framework for creating videos programmatically using React. Video tools for the agent era. Make videos agentically, interactively, or programmatically — React Code is the source of truth. Switch your workflow at any point.',
    plainDesc: '用写React代码的方式做视频，不用PR、不用剪映。前端工程师用熟悉的技术栈就能做视频，特别适合需要批量生成视频、数据可视化动画、产品演示的场景。',
    capabilities: [
      '编程式视频创作 — 用React组件定义每一帧画面',
      'Agent视频生成 — 配合AI编码代理自动生成视频',
      '交互式编辑 — Studio拖拽编辑动画时间线',
      '批量渲染 — 数据驱动批量生成百万级个性化视频',
      '设计系统 — 创建可复用的动画资产库',
      '多端渲染 — 支持Node.js/Lambda/Vercel/客户端渲染',
    ],
    components: [
      'Composition — 定义视频尺寸、帧率、时长',
      'Sequence — 精确控制时间线序列',
      'AbsoluteFill — 全屏填充容器组件',
      'useCurrentFrame — 获取当前帧的Hook',
      'spring() — 物理弹性动画函数',
    ],
    examples: [
      'GitHub Unwrapped — 个性化年度回顾视频，数据驱动生成',
      'Fireship "This video was made with code" — 纯代码生成视频演示',
    ],
    suitableFor: [
      { type: '视频编辑平台', desc: '在线视频编辑器、动画制作工具、动态图形设计平台' },
      { type: '内容创作SaaS', desc: '营销视频批量生成、社交媒体内容自动化、广告视频工厂' },
      { type: '数据可视化平台', desc: '数据驱动的动态图表视频、实时数据报告动画、仪表盘录屏' },
      { type: '产品演示工具', desc: '产品功能演示动画、教程视频自动生成、SaaS onboarding视频' },
      { type: '教育平台', desc: '课程动画制作、知识点讲解视频、互动教学内容生成' },
      { type: '企业品牌工具', desc: '品牌动画资产库、企业宣传视频模板系统、活动视频批量生成' },
    ],
    workflow: [
      { step: 1, title: '项目初始化', desc: '运行 npx create-video@latest 创建Remotion项目，选择模板或空白项目' },
      { step: 2, title: '定义Composition', desc: '设置视频的宽度、高度、帧率(fps)、总时长(durationInFrames)' },
      { step: 3, title: '编写React组件', desc: '用useCurrentFrame获取当前帧，结合CSS/SVG/Canvas/WebGL定义动画效果' },
      { step: 4, title: '预览调试', desc: '用Remotion Studio实时预览视频，调整时间线、参数和动画曲线' },
      { step: 5, title: '渲染输出', desc: '调用renderMedia()或CLI命令，通过Chrome Headless+FFmpeg渲染为MP4/WebM' },
      { step: 6, title: '部署自动化', desc: '部署到Lambda/Vercel/自有服务器，实现数据驱动的批量视频渲染管线' },
    ],
    pageDemos: [
      { type: 'landing', title: '视频创作平台官网', desc: '展示Remotion能力的营销落地页' },
      { type: 'dashboard', title: '视频渲染管理后台', desc: '批量视频任务管理和渲染状态监控' },
      { type: 'mobile-app', title: '移动端视频编辑器', desc: '手机端视频创作和预览界面' },
    ],
    conversations: [
      { q: '帮我做一个产品发布的宣传视频', a: '使用Remotion创建Composition，用Sequence组织开场、产品展示、CTA三个段落，spring()做元素入场动画', output: '生成30秒产品宣传视频React代码' },
      { q: '如何用数据批量生成1000个个性化视频？', a: '用renderMedia()循环遍历数据集，每条数据作为inputProps传入组件，Lambda并行渲染', output: '批量渲染脚本和数据驱动组件' },
      { q: '做一个数据可视化的动态图表视频', a: '用recharts或d3结合useCurrentFrame，让柱状图/折线图随帧增长，添加数字计数动画', output: '数据可视化动画视频组件' },
      { q: '视频里的文字怎么加打字机效果？', a: '用useCurrentFrame计算当前应显示的字符数，slice()截取文本，配合光标闪烁动画', output: '打字机效果文字组件' },
      { q: '怎么把Remotion集成到我的SaaS产品里？', a: '用@remotion/player嵌入播放器，后端用Lambda渲染，用户自定义参数后触发生成', output: 'SaaS视频生成集成方案代码' },
    ],
    prompts: [
      { title: '产品宣传视频', text: '用Remotion创建一个30秒的SaaS产品宣传视频，包含品牌开场、3个核心功能展示、用户评价、CTA结尾，使用现代简约设计风格' },
      { title: '数据可视化动画', text: '创建一个数据可视化视频，展示年度销售数据增长，包含动态柱状图、折线图、数字计数动画，时长20秒' },
      { title: '教程讲解视频', text: '制作一个编程教程的开场视频，包含标题动画、目录展示、讲师介绍，使用科技感深色主题' },
      { title: '社交媒体短视频', text: '生成一个15秒的Instagram Reels视频，竖屏9:16，包含产品图片轮播、价格标签、行动号召，适合电商营销' },
      { title: '品牌动画Logo', text: '创建一个5秒的品牌Logo动画，包含粒子汇聚效果、文字渐入、弹性缩放，输出透明背景WebM' },
    ],
    userReviews: {
      rating: 4.7,
      count: 1280,
      summary: 'Remotion是视频即代码领域的标杆项目，51k+ stars证明了其受欢迎程度。前端工程师可以用熟悉的React技术栈创作视频，特别适合批量生成和数据驱动场景。学习曲线平缓，但复杂动画仍需深入理解帧编程模型。商业使用需注意公司许可要求。',
      pros: [
        '用React写视频，前端工程师零学习成本上手',
        '视频即代码，可版本控制、可复用、可自动化',
        '数据驱动批量渲染，适合个性化视频生成',
        '支持CSS/SVG/Canvas/WebGL，视觉表现力强',
        'Remotion Studio实时预览，调试体验好',
        '活跃的社区生态，628+ releases持续更新',
        '多端渲染支持，Lambda/Vercel/Node.js均可',
        'AI Agent友好，配合Codex/Claude自动生成视频',
      ],
      cons: [
        '商业使用需公司许可（4人以上团队）',
        '复杂动画需要理解帧编程模型，有学习曲线',
        '渲染依赖Chrome Headless，服务器资源消耗较大',
        '相比专业视频软件，视觉特效能力有限',
        '音频处理功能相对基础',
      ],
      articles: [
        { title: 'Remotion 深度解析:用 React 写视频，前端工程师的 After Effects 替代方案', source: '博客园', url: 'https://www.cnblogs.com/jzssuanfa/p/20492813' },
        { title: '以前做视频靠时间，现在做视频靠提示词——Codex+Remotion体验记', source: 'CSDN', url: 'https://blog.csdn.net/weixin_74888502/article/details/162003231' },
        { title: 'Remotion Review: Features, Pros & Cons and how it compares to alternatives', source: 'Websites2Know', url: 'https://websites2know.com/remotion-review/' },
        { title: '使用 Remotion 打造专业级产品动画视频', source: 'CSDN', url: 'https://blog.csdn.net/u010475928/article/details/160267142' },
        { title: 'remotion:用 React 组件以代码方式生成视频', source: 'X-CMD', url: 'https://cn.x-cmd.com/install/remotion/' },
      ],
    },
  },
  {
    id: 'awesome-design-md-jp',
    name: 'Awesome Design MD JP',
    category: '综合设计系统',
    github: 'https://github.com/kzhrknt/awesome-design-md-jp',
    website: 'https://github.com/kzhrknt/awesome-design-md-jp',
    stars: 1200,
    version: 'v1.0.0',
    updated: '2026-08',
    triggerSummary: '当你需要 AI 生成准确的日本语 UI 时就调用它 —— 480+ 日本网站设计规范，含 CJK 排版、禁则处理、和文フォントチェーン',
    officialIntro: 'A curated collection of DESIGN.md files for Japanese web services — enabling AI agents to generate accurate Japanese UI with proper typography, font stacks, and typographic rules.',
    plainDesc: '这是一个日本网站设计规范的大合集。简单说，就是把 Apple、MUJI、Mercari 这些日本知名网站的设计风格、字体、颜色、排版规则都整理成了 AI 能读懂的 DESIGN.md 文件。你要做日本语网站时，把对应的 DESIGN.md 给 AI，它就能生成符合日本网站风格的 UI，不会出现字体不对、行间距太窄、标点符号跑到行首这种问题。',
    capabilities: [
      '480+ 日本网站设计规范',
      'CJK 排版规则（禁則処理）',
      '和文フォントフォールバックチェーン',
      'OpenType プロポーショナル組版',
      '混植ルール（和文+欧文）',
      'デザイントークン可視化プレビュー',
    ],
    components: [
      'DESIGN.md テンプレート',
      'preview.html ショーケース',
      'gallery.html ギャラリー',
      'デザイントークン抽出スクリプト',
      'CJK タイポグラフィ規約',
    ],
    examples: [
      { title: 'Apple Japan デザインシステム', desc: 'Apple 日本公式サイトの DESIGN.md' },
      { title: 'MUJI 無印良品 デザイン', desc: '無印良品公式サイトの DESIGN.md' },
    ],
    suitableFor: [
      { type: '日本語 EC サイト', desc: 'メルカリ・楽天・Amazon JP 风格の电商网站' },
      { type: '日本語コーポレートサイト', desc: '伊藤忠・リクルート・ソニー风格の企业官网' },
      { type: '日本語メディア/ブログ', desc: 'はてな・note・Zenn风格の媒体网站' },
      { type: '日本語 SaaS ダッシュボード', desc: 'freee・マネーフォワード风格の管理画面' },
      { type: '日本語モバイルアプリ', desc: 'PayPay・LINE・メルカリ风格の移动端 UI' },
      { type: '多言語対応サイト', desc: '日英双语或多语言网站' },
    ],
    workflow: [
      { step: 1, title: '対象サイト選択', desc: '从 480+ 日本网站中选择与目标项目最接近的 DESIGN.md' },
      { step: 2, title: 'DESIGN.md 読み込み', desc: '读取对应的 DESIGN.md 文件，提取品牌色、字体、排版规则' },
      { step: 3, title: 'デザイントークン抽出', desc: '从 DESIGN.md 中提取设计令牌，转换为 CSS 变量或 Tailwind 配置' },
      { step: 4, title: 'CJK タイポグラフィ適用', desc: '应用日本语排版规则：禁则处理、字间距、行间距、和文フォントチェーン' },
      { step: 5, title: 'UI 生成', desc: '基于设计规范生成 UI 组件和页面，确保风格一致' },
      { step: 6, title: '品質チェック', desc: '检查日本语排版质量：禁则处理、字体回退、行间距、混植规则' },
    ],
    articles: [
      { title: 'awesome-design-md-jp：日本語UI DESIGN.md集', source: 'AI Heartland', url: 'https://ai-heartland.com/agent/awesome-design-md-jp/' },
      { title: 'AI時代のデザインシステム「DESIGN.md」入門', source: 'エレファンキューブ', url: 'https://www.elephancube.co.jp/2026/04/design-md/' },
      { title: 'Design.mdとは何か、使い方は？', source: 'Banani', url: 'https://www.banani.co/ja/blog/design-md-guide' },
      { title: 'DESIGN.md という新しいフォーマットの衝撃', source: 'unType', url: 'https://www.untype.jp/blog/design-systems-design-md-format' },
    ],
    userReviews: {
      rating: 4.5,
      count: 320,
      summary: 'Awesome Design MD JP 是日本语 UI 设计规范的权威合集，480+ 日本知名网站的 DESIGN.md 文件覆盖电商、企业、媒体、SaaS 等全场景。最大价值在于解决了 AI 生成日本语 UI 时的排版痛点——禁则处理、和文フォントチェーン、行间距、混植规则等。对于需要做日本市场的产品团队，这是不可或缺的参考资源。',
      pros: [
        '480+ 日本知名网站设计规范，覆盖全行业场景',
        '完整的 CJK 排版规则，解决 AI 生成日本语 UI 的排版痛点',
        '和文フォントフォールバックチェーン，确保字体显示正确',
        '每个 DESIGN.md 都有 preview.html 可视化预览',
        '持续更新，每月新增多个网站的设计规范',
        '基于 Google Stitch 提唱的 DESIGN.md 标准格式',
        'AI Agent 友好，可直接作为上下文输入生成 UI',
        '开源免费，MIT 许可，可商业使用',
      ],
      cons: [
        '仅覆盖日本网站，不包含其他 CJK 语言（中文、韩文）',
        '设计规范是静态提取，可能与网站最新设计有偏差',
        '需要手动选择对应的 DESIGN.md，没有智能推荐功能',
        '部分网站的规范可能不够详细，缺少组件级设计',
        '对于非日本市场的产品，参考价值有限',
      ],
      articles: [
        { title: 'awesome-design-md-jp：日本語UI DESIGN.md集', source: 'AI Heartland', url: 'https://ai-heartland.com/agent/awesome-design-md-jp/' },
        { title: 'AI時代のデザインシステム「DESIGN.md」入門', source: 'エレファンキューブ', url: 'https://www.elephancube.co.jp/2026/04/design-md/' },
        { title: 'Design.mdとは何か、使い方は？', source: 'Banani', url: 'https://www.banani.co/ja/blog/design-md-guide' },
      ],
    },
  }

];
